### ISSUE TITLE
Format codes with literal strings produce invalid XML

### ISSUE THREAD

**Issue by md5** [caxlsx/caxlsx#109]
When using the `"text"` construct in a `format_code` value to provide a literal value (e.g. `"-"` as commonly used in place of `0` in accounting number formats), the resulting `numFmt` ends up containing unescaped double quotes which means the `styles.xml` part will be ill-formed and Excel will throw it out.  A workaround would be to put `&quot;` in the `format_code` instead, but this should not be necessary. What's more, if anyone has already used this workaround, any attempt to fix this library by escaping reserved characters as XML entities will break those existing workarounds.

**Comment by noniq** [comment]
As you point out, changing this would be a backwards incompatible change. It would make sense, but it can't be done before the next major version.

Maybe in the meantime we could add code that raises if the given `format_code` would produce ill-formed XML? Could this break any legitimate use cases?

**Comment by md5** [comment]
I suppose invalid strings including `&` could also be considered, but that's going to be trickier to get 100% right

**Comment by md5** [comment]
Putting UTF encoding aside, I think you would raise if you see `"` at all or `&` when it is not part of `&amp;`, `&quot;`, `&apos;`, `&lt;`, `&gt;`, or a numeric `&#NNN;` or `&#xHHH;` sequence. I'm about 90% confident in that answer given how many edge cases XML has, but we know that the attributes are being delimited by double quotes and that no external entities are being defined since the library is producing the rest of the document.

**Comment by straydogstudio** [comment]
@noniq @md5 Any thoughts on what our next steps should be on this issue?
