### ISSUE TITLE
Pivot table is invalid when set more than one column in data field

### ISSUE THREAD

**Issue by ctulhuweb** [caxlsx/caxlsx#110]
I try to add 'Customers' column in pivot_table.data. Microsoft excel throws error.

Example:
```
require 'caxlsx'

p = Axlsx::Package.new
wb = p.workbook

wb.add_worksheet(name: 'Basic Worksheet') do |sheet|
  sheet.add_row ['Month', 'Year', 'Type', 'Sales', 'Customers', 'Region']

  # Generate some data
  30.times do
    sheet.add_row [
      ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'].sample,
      [2010, 2011, 2012].sample,
      ['Meat', 'Dairy', 'Beverages', 'Produce'].sample,
      rand(5000),
      rand(100),
      ['East', 'West', 'North', 'South'].sample
    ]
  end

  sheet.add_pivot_table 'H4:M17', 'A1:F31' do |pivot_table|
    pivot_table.rows = ['Month', 'Year']
    pivot_table.data = ['Sales', 'Customers']
    pivot_table.pages = ['Region']
  end
end
p.serialize 'pivot_table_example.xlsx'
```

**Comment by straydogstudio** [comment]
@ctulhuweb Does the spreadsheet throw an error if it is opened in OpenOffice or some other spreadsheet application?

**Comment by diego-alay** [comment]
> @ctulhuweb Does the spreadsheet throw an error if it is opened in OpenOffice or some other spreadsheet application?

Opening the spreadsheet works in libreoffice, but doesn't work using Microsoft Excel.

**Comment by rolftimmermans** [comment]
I ran into the same issue. My pivot table definition with only **rows** and **data**:

```
      sheet.add_pivot_table "A1:E2", pivot_table_ref do |pivot_table|
        pivot_table.rows = [
          "Date",
          "Name",
        ]

        pivot_table.data = [
          {ref: "Gross amount", num_fmt: 2},
          {ref: "Net amount", num_fmt: 2},
        ]
      end
``

It **only** works for me in Excel when I make the following **changes to the XML**:

1. Remove `<colItems count="1"><i/></colItems>` and replace it with `<colFields count="1"><field x="-2"/></colFields>`
2. Remove `dataOnRows="1"`

My extremely dirty hack to fix this:
```
class Axlsx::PivotTable
  alias_method :orig_to_xml_string, :to_xml_string

  def to_xml_string(zip = "")
    str = ""
    orig_to_xml_string(str)

    str.gsub!(
      '<colItems count="1"><i/></colItems>',
      '<colFields count="1"><field x="-2"/></colFields>',
    )

    str.gsub!(
      'dataOnRows="1"',
      "",
    )

    zip << str
end
```

**Comment by diego-alay** [comment]
> I ran into the same issue. My pivot table definition with only **rows** and **data**:
> 
> ```ruby
> sheet.add_pivot_table "A1:E2", pivot_table_ref do |pivot_table|
>   pivot_table.rows = [
>     "Date",
>     "Name",
>   ]
> 
>   pivot_table.data = [
>     {ref: "Gross amount", num_fmt: 2},
>     {ref: "Net amount", num_fmt: 2},
>   ]
> end
> ```
> 
> It **only** works for me in Excel when I make the following **changes to the XML**:
> 
>     1. Remove `<colItems count="1"><i/></colItems>` and replace it with `<colFields count="1"><field x="-2"/></colFields>`
> 
>     2. Remove `dataOnRows="1"`
> 
> 
> My extremely dirty hack to fix this:
> 
> ```ruby
> class Axlsx::PivotTable
>   alias_method :orig_to_xml_string, :to_xml_string
> 
>   def to_xml_string(zip = "")
>     str = ""
>     orig_to_xml_string(str)
> 
>     str.gsub!(
>       '<colItems count="1"><i/></colItems>',
>       '<colFields count="1"><field x="-2"/></colFields>',
>     )
> 
>     str.gsub!(
>       'dataOnRows="1"',
>       "",
>     )
> 
>     zip << str
>   end
> end
> ```

You are awesome !!!. Thanks works for me :)

**Comment by simi** [comment]
This makes sense to me. Can you open PR with related changes?

Just check if `columns` is empty and prevent adding `dataOnRows="1"` at https://github.com/caxlsx/caxlsx/blob/6702f7e5c4a7494ab5007a0e42bbec2e760bcad3/lib/axlsx/workbook/worksheet/pivot_table.rb#L176

and change handling empty `columns` later at https://github.com/caxlsx/caxlsx/blob/6702f7e5c4a7494ab5007a0e42bbec2e760bcad3/lib/axlsx/workbook/worksheet/pivot_table.rb#L199 as well.

If you can also provide original broken file and fixed one and do some testing locally at various programs, that would be nice. I have not real Excel (any version) around for now.

**Comment by westonganger** [comment]
Link to original issue within axlsx is here: https://github.com/randym/axlsx/issues/404
