### ISSUE TITLE
Allow border style to accept an Array

### ISSUE THREAD

**Issue by westonganger** [caxlsx/caxlsx#111]
As clearly described in https://github.com/axlsx-styler-gem/axlsx_styler/issues/31

It is currently very difficult to apply different border styles to different sides of a cell.

As proposed by @md5, it would be useful to allow the `:border` style to accept an Array. This would allow to maintain backwards compatibility with existing code.

Proposed Code:

```ruby
workbook.styles.add_style(
  border: [
    { style: :thick, color: '000' },
    { style: :thick, edges: [:top, :bottom] },
    { style: :double, edges: [:left, :right] }
  ]
)
```

Current Code to Achieve desired result:

```ruby
workbook.styles.add_style(
  border: { style: :none, color: nil }, ### Note: the need for dummy `:border` values just to get them to look at the other border_* properties
  border_top: { style: :thin, color: '000000' },
  border_right: { style: :thick, color: '000000' },
  border_bottom: { style: :thin, color: '000000' },
  border_left: { style: :thick, color: '000000' }
)
```

**Comment by simi** [comment]
@westonganger sounds good to me. Would you like to contribute this? I think you can take a look at https://github.com/caxlsx/caxlsx/blob/6702f7e5c4a7494ab5007a0e42bbec2e760bcad3/lib/axlsx/stylesheet/styles.rb#L319-L340 and add support for `Array` argument and handle it in there.

**Comment by straydogstudio** [comment]
This has been merged
