### ISSUE TITLE
Cell errors on large integers

### ISSUE THREAD

**Issue by rileys** [caxlsx/caxlsx#113]
Cell data type autodetection will set a cell to integer when the integer is too large to be used with xlsx.

This can cause cell errors and make it so the file can't be opened with some software.

**Comment by ricopper** [comment]
This is probably an invalid use case, it's unlikely a huge (200 character) integer would be inputted, this can be closed.

**Comment by rileys** [comment]
This is probably an invalid use case, very unlikely someone will enter a 200 character integer.

**Comment by straydogstudio** [comment]
@rileys Thanks for creating and closing it. I agree, 200 characters is pretty high.
