### ISSUE TITLE
NoMethodError (undefined method `match' for nil:NilClass)

### ISSUE THREAD

**Issue by dennisbulgatz** [caxlsx/caxlsx#114]
Method causing error.

    def cell_type_from_value(v)
      if v.is_a?(Date)
        :date
      elsif v.is_a?(Time)
        :time
      elsif v.is_a?(TrueClass) || v.is_a?(FalseClass)
        :boolean
      elsif v.to_s =~ Axlsx::NUMERIC_REGEX && v.respond_to?(:to_i)
        :integer
      elsif v.to_s =~ Axlsx::SAFE_FLOAT_REGEX && v.respond_to?(:to_f)
        :float
      **elsif (matchdata = v.to_s.match(MAYBE_FLOAT_REGEX)) && (Float::MIN_10_EXP..Float::MAX_10_EXP).cover?(matchdata[:exp].to_i) && v.respond_to?(:to_f)**
        :float
      elsif v.to_s =~ Axlsx::ISO_8601_REGEX
        :iso_8601
      elsif v.is_a? RichText
        :richtext
      else
        :string
      end
    end

Corrected Method
    def cell_type_from_value(v)
      if v.is_a?(Date)
        :date
      elsif v.is_a?(Time)
        :time
      elsif v.is_a?(TrueClass) || v.is_a?(FalseClass)
        :boolean
      elsif v.to_s =~ Axlsx::NUMERIC_REGEX && v.respond_to?(:to_i)
        :integer
      elsif v.to_s =~ Axlsx::SAFE_FLOAT_REGEX && v.respond_to?(:to_f)
        :float
      **elsif v.respond_to?(:to_f) && (matchdata = v.to_s.match(Axlsx::MAYBE_FLOAT_REGEX)) && (Float::MIN_10_EXP..Float::MAX_10_EXP).cover?(matchdata[:exp].to_i)** 
        :float
      elsif v.to_s =~ Axlsx::ISO_8601_REGEX
        :iso_8601
      elsif v.is_a? RichText
        :richtext
      else
        :string
      end
    end

NoMethodError (undefined method `match' for nil:NilClass):
  
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/cell.rb:458:in `cell_type_from_value'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/cell.rb:42:in `initialize'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:159:in `new'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:159:in `block in array_to_cells'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:153:in `each'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:153:in `each_with_index'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:153:in `array_to_cells'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:36:in `initialize'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/worksheet.rb:412:in `new'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/worksheet.rb:412:in `add_row'

**Comment by kiskoza** [comment]
Thanks for submitting this issue :)

Here is a `git diff` version of the change request above

```diff
diff --git a/lib/axlsx/workbook/worksheet/cell.rb b/lib/axlsx/workbook/worksheet/cell.rb
index 51a1449..168d304 100644
--- a/lib/axlsx/workbook/worksheet/cell.rb
+++ b/lib/axlsx/workbook/worksheet/cell.rb
@@ -455,7 +455,7 @@ module Axlsx
         :integer
       elsif v.to_s =~ Axlsx::SAFE_FLOAT_REGEX && v.respond_to?(:to_f)
         :float
-      elsif (matchdata = v.to_s.match(MAYBE_FLOAT_REGEX)) && (Float::MIN_10_EXP..Float::MAX_10_EXP).cover?(matchdata[:exp].to_i) && v.respond_to?(:to_f)
+      elsif v.respond_to?(:to_f) && (matchdata = v.to_s.match(Axlsx::MAYBE_FLOAT_REGEX)) && (Float::MIN_10_EXP..Float::MAX_10_EXP).cover?(matchdata[:exp].to_i)
         :float
       elsif v.to_s =~ Axlsx::ISO_8601_REGEX
         :iso_8601
```

As far as I can see the only changes are that @dennisbulgatz moved the `v.respond_to?(:to_f)` check to the beginning of the line and added `Axlsx::` to the constant.

The error could be caused by an object which gives back `nil` for `to_s` - not sure if it's and error in Axlsx, we should expect `to_s` to work (and provide an empty string instead of nil), we definitely need a way to reproduce it before jumping into working on it.

On the other hand, checking if the object responds to `to_f` requires less computation than running the regexp match, so we could handle this change request as a performance improvement.

**Comment by dennisbulgatz** [comment]
Thanks you!  I hope this simple fix can get incorporated without the test case to support it. Because I get the error using a rails app, running an excel export, it is not a simple matter to find the data causing this crash.  I could add a begin rescue block to dump the offending data if needed, and if you send me a sample stand along program, can try to tweak it to reproduce the error.

**Comment by dennisbulgatz** [comment]
Is there a branch with the fix incorporated I can use?  I'm not very familiar with the fix process.

**Comment by dennisbulgatz** [comment]
I did not write the active_scaffold_export gem, which is using caxlsx to create excel sheets from a Ruby on Rails web site built with Active_scaffold.  So me changing the call is not reasonable-way too much to learn.  But what I can do is better trap the error so I can see what is getting sent in, using a begin-rescue block.

**Comment by simi** [comment]
@dennisbulgatz is it this gem? https://github.com/activescaffold/active_scaffold

**Comment by dennisbulgatz** [comment]
Yes, the gems above are correct.  I put together a short tutorial on how to build a web site if you are interested. But I found the problem, and was able to correct.  The object sent by AS to the method in caxlsx is an ActiveRecord Object, and it must have to_s defined as a method in the model. If to_s returns nil, it causes the error above.  So, I fixed this with a check that to_s always returns a string, never nil.  Thank your for your help.  I suggest that if v is nil, you select string for the cell type and be done with it!  No reason to have an unhandled exception.

**Comment by dennisbulgatz** [comment]
https://github.com/activescaffold/active_scaffold/wiki/Rails-6-setup-on-Mac-Catalina-or-BigSur,-with-Brew is the tutorial.  Check it out.

**Comment by kiskoza** [comment]
I followed your guide word by word and didn't get the error you described, it all went fine for me, I wasn't able to reproduce the issue.

The problem isn't that `v` is nil, because `nil.to_s` gives back an empty string and `cell_type_from_value` will choose the `:string` type. The problem is when a `to_s` is not doing what is should do and return a non-string value, like `nil`. I'm still thinking that this is a problem outside of Caxlsx.

**Comment by dennisbulgatz** [comment]
All, from what I can tell, the underlying issue is caused because the ActiveRecord Class sometimes returns nil on a to_s, which I believe is a bug in ActiveRecord that is data dependent.  The fix I proposed above (re-arranging the order of the conditional tests) is an innocuous band-aid, and hope you will consider adding it.  

I fixed this for my application by over-riding the to_s method in the models that inherit from ActiveRecord.  

This team is awesome in how quickly you got back to me on this, and if/when I get more bandwidth, may start trying to more actively contribute.

**Comment by simi** [comment]
Thanks for the info @dennisbulgatz. I'll check the ActiveRecord, maybe I'll find more info.

**Comment by simi** [comment]
If you'll be able to share data to reproduce, that would be helpful.

**Comment by dennisbulgatz** [comment]
I will see if I can put together an application with a few records that reproduces the error.
