### ISSUE TITLE
Add Github Actions CI Workflow

### ISSUE THREAD

**Issue by westonganger** [caxlsx/caxlsx#118]
Need to add a CI. Should test multiple ruby versions. Will create a PR for this, I have a good template.

**Comment by westonganger** [comment]
Oops I see the travis integration is actually active. Feel free to close.

**Comment by simi** [comment]
@westonganger that would be actually still welcomed since future of free Travis CI program is currently not clear and it is common to migrate CI to GitHub Actions.

**Comment by westonganger** [comment]
Ok sounds good will do
