### ISSUE TITLE
is it possible to add image background for the page?

### ISSUE THREAD

**Issue by laptopmutia** [caxlsx/caxlsx#121]
I have a A4 background image and want to make it as a background for my spreadsheet

it have centered image background and a header with company logo

related issue: 
https://github.com/randym/axlsx/issues/408

**Comment by straydogstudio** [comment]
@laptopmutia I don't see anything in the code for setting the background of the whole sheet.

@simi @noniq @randym @kiskoza @westonganger Does anyone know about this? Or if there is an XLSX standard that could eventually be implemented? I see a &G "picture as background" code under header_and_footer_codes.md but nothing else.

**Comment by westonganger** [comment]
Yes reverse engineering is the way forward here.
