### ISSUE TITLE
Feature Request Support for table calculatedColumnFormula

### ISSUE THREAD

**Issue by LyzioOh** [caxlsx/caxlsx#124]
In order to start i would like to thanks for the amazing work done. 👍 

I 'm looking for a way to add a **calculatedColumnFormula**  to a table. IMHO calculatedColumnFormula brings 2 benefits :

- The formula is expanded when a new row is added.
- It table cell validation to look for inconsistency. (One cell in the column , does not have the same formula)

I would like to know :

- Does this feature is already implemented ? 
- Does Pr are Welcome ? 

## Some retroengineering
````xml
<table mc:Ignorable="xr xr3" id="6" xr:uid="{00000000-000C-0000-FFFF-FFFF05000000}" name="farm" displayName="farm" ref="A1:D5" totalsRowShown="0">
<autoFilter ref="A1:J3" xr:uid="{00000000-0009-0000-0100-000006000000}"/>
<tableColumns count="10">
<tableColumn id="1" xr3:uid="{00000000-0010-0000-0500-000001000000}" name="name"/>
<tableColumn id="3" xr3:uid="{00000000-0010-0000-0500-000003000000}" name="dog"/>
<tableColumn id="4" xr3:uid="{00000000-0010-0000-0500-000004000000}" name="cat"/>
<tableColumn id="10" xr3:uid="{3ED19250-BFE2-FF42-991C-8FC951DC906B}" name="animals" dataDxfId="0">
  <calculatedColumnFormula>
    farm[dog] + farm[cat]
  </calculatedColumnFormula>
</tableColumn>
</table>
````

**Comment by kiskoza** [comment]
hi. caxlsx does not have this feature yet, feel free to implement it. if you need any help, you can reach us here or via our slack channel
