### ISSUE TITLE
Change general coding style from Code Style from String Concatenation to String Interpolation

### ISSUE THREAD

**Issue by westonganger** [caxlsx/caxlsx#126]
> For More Context on this Issue, please read: https://github.com/caxlsx/caxlsx/pull/123

I propose that we switch the coding style from String Concatenation to String Interpolation

Before:
```ruby
str << ('<pivotTableDefinition xmlns="' << XML_NS << '" name="' << name << '" cacheId="' << cache_definition.cache_id.to_s << '"  dataOnRows="1" applyNumberFormats="0" applyBorderFormats="0" applyFontFormats="0" applyPatternFormats="0" applyAlignmentFormats="0" applyWidthHeightFormats="1" dataCaption="Data" showMultipleLabel="0" showMemberPropertyTips="0" useAutoFormatting="1" indent="0" compact="0" compactData="0" gridDropZones="1" multipleFieldFilters="0">')


```

After (possible format):
```ruby
str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0" applyFontFormats="0" applyPatternFormats="0" applyAlignmentFormats="0" applyWidthHeightFormats="1" dataCaption="Data" showMultipleLabel="0" showMemberPropertyTips="0" useAutoFormatting="1" indent="0" compact="0" compactData="0" gridDropZones="1" multipleFieldFilters="0">)
```

Goals:

- Improve ability to comprehend/scan code quickly
- Same or improved performance

Regarding Static Analysis Tools / Code Formatters:

I am NOT a fan of introducing static analysis tools such as `rubocop` on open source libraries. However if deemed desirable by the team then `standardrb` would likely be a very wise choice over plain rubocop setup.

**Comment by simi** [comment]
IMHO the best solution would be to not concat or interpolate strings at all and use some XML builder (https://github.com/tenderlove/builder) instead. WDYT?

**Comment by westonganger** [comment]
Switching to a builder seems like it would require a ton of code changes, making a much greater risk of introducing new bugs. Personally, I think we should stay with strings.

**Comment by noniq** [comment]
@simi Fun fact: Axlsx *did* initially use a builder (Nokogiri), but it was removed quite a long time ago (see https://github.com/caxlsx/caxlsx/commit/22a341841f191a5aa00e87b1f166b4f25cc67f0a) because of concerns regarding memory usage and speed. 

I’m quite sure that using Nokogiri wasn’t an ideal choice to begin with. Maybe using [[builder]](https://github.com/jimweirich/builder) or something similar would be possible without too much of an overhead? Especially considering that Ruby’s internal handling of strings and objects is way more officient nowadays.

**Comment by westonganger** [comment]
[ohler55/ox](https://github.com/ohler55/ox) would likely be the high performance & maintained builder gem you would want to use

**Comment by kiskoza** [comment]
There are multiple topics here:

1. Using rubocop / standardrb: They are great tools to make something unified, I personally love them. However, on an open source project, we should use them carefully. I would say we should pick some of the rules we want to apply and do not use all of them. For example it would be helpful to check the syntax of string manupulation we agree on, but I wouldn't bring unnecessary rules to the table to keep contributions as easy as we could. And definitely don't introduce a new rule that reformats the whole project unless we all agree on that it brings value.

2. String interpolation / string concatenation: I don't think the `%Q()` style is any better, it still produces a long lines and hard-to-read syntax. I'm not blaming the `%Q()`, it's beacause we already have cryptic xml we want to manipulate. I think it would be nicer to use heredocs, something like this or having one xml tag per line (not breaking the attributes into new lines). The point is we don't need to start all lines with `str << ...` but have one template per method.
```ruby
<<~XML
  <pivotTableDefinition 
    xmlns="#{XML_NS}"
    name="#{name}"
    cacheId="#{cache_definition.cache_id.to_s}"
    #{'dataOnRows="1"' if data.size <= 1}
    applyNumberFormats="0"
    applyBorderFormats="0" 
    applyFontFormats="0" 
    applyPatternFormats="0" 
    applyAlignmentFormats="0"
    applyWidthHeightFormats="1" 
    dataCaption="Data" 
    showMultipleLabel="0" 
    showMemberPropertyTips="0" 
    useAutoFormatting="1" 
    indent="0" 
    compact="0" 
    compactData="0" 
    gridDropZones="1" 
    multipleFieldFilters="0">
    <location
      firstDataCol="1" 
      firstDataRow="1"
      firstHeaderRow="1" 
      ref="#{ref}" />
   ....
  </pivotTableDefinition>
XML
```

or

```ruby
<<~XML
  <pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0" applyFontFormats="0" applyPatternFormats="0" applyAlignmentFormats="0" applyWidthHeightFormats="1" ="Data" showMultipleLabel="0" showMemberPropertyTips="0" useAutoFormatting="1" indent="0" compact="0" compactData="0" gridDropZones="1" multipleFieldFilters="0">
    <location firstDataCol="1" firstDataRow="1" firstHeaderRow="1" ref="#{ref}" />
   ....
  </pivotTableDefinition>
XML
```

3. Builder: They sound okay, but not sure if they could help without some refactoring on our classes. If we need to build a new object and call an `Ox.dump` or `to_xml` on it, then it will definitely slow down the generation (see the problem with Nokogiri). If we can change our existing models to be dumpable by Ox (or similar project) then it could help a bit. I'm not against having a builder as it would reduce the number of issues with invalid xmls / attributes, however with a cost. It would be nice to see some benchmark with one of our classes.
