### ISSUE TITLE
Implementing the 'axlsx' gems in new project

### ISSUE THREAD

**Issue by JenniferMB** [caxlsx/caxlsx#13]
Please forgive the off topic question, but the SO community can be mean sometimes....

Which gems do I need for a brand new application? Do I need axlsx AND caxlsx? Do I still need axlsx_rails? Or is there a caxlsx_rails gem? And what about acts_as_xlsx? Do I need that too? Any other variations of the *xlsx* gem family out there I should know about? My head is spinning

**Comment by simi** [comment]
There are 2 families right now. The original one called `axlsx` and this one called `caxlsx` (addition c stands for community). Since original author had not time anymore to maintain `axlsx` family this community one was created.

You need to use only one of those two. If you would like to use the latest maintained version, I suggest to use `caxlsx`. You can check in readmes per particular projects what each project provides.

**Comment by JenniferMB** [comment]
Thank you so much for your reply. Will there be a community version of
axlsx_rails, and acts_as_xlsx? I have been terribly confused by the stale
documentation that instructed me to add 'acts_as_xlsx' to my model! I
discovered that it is not needed at all anymore, so that was a victory, but
I have been struggling with gem install dependencies. My development
environment is not permitted access to GitHub (or the internet at all) so
matching the right gem versions and managing to copy them to my environment
has been a challenge. But I am struggling forward, thank you for answering
my question.

**Comment by simi** [comment]
It looks like you're hitting this problem - https://github.com/caxlsx/caxlsx/issues/9. Can you please take a look if you use 3.0.1 in gemfile?

You can use `gem "caxlsx", "~> 3.0.1"` in your Gemfile and run `bundle update caxlsx` to ensure you're on that or later version.

**Comment by JenniferMB** [comment]
I am using "axslx" (3.0.0.pre) so I will gladly try to replace it with the
"caxlsx" (3.0.1) which I do have.

**Comment by JenniferMB** [comment]
You are killin' me with these dependencies!

**Comment by JenniferMB** [comment]
Had to update rubyzip and nokogiri, then had to restore the previous
version of rubyzip because selenium-webdriver could not resolve its
dependency on rubyzip >= 1.2.2 (even after updating the selenium-webdriver
gem). Uninstalled caxlsx and reverted to axlsx. All these dependencies
might work themselves out under normal circumstances, but as I said before,
I cannot connect to a gem repository from my development machine - I must
copy them and manually install/update each one.

**Comment by inopinatus** [comment]
The following - all current versions - have no dependency clashes:

caxlsx 3.0.1  
axlsx_rails 0.6.0  
acts_as_caxlsx 1.0.6 (currently only available as source from Github)  
selenium-webdriver 3.142.6  
rubyzip 1.3.0  
nokogiri 1.10.4  

The community is in a transitional period, but the dependencies are sound. `acts_as_caxlsx` isn't polished for release yet, but when working offline, source can still be retrieved from Github and built as a binary gem for transport to the offline environment.

**Comment by JenniferMB** [comment]
I did a force install and I am now operational again. Thank you for your
reply.

For your information, I have run across a similar issue before with a
different gem, where all the dependencies seem to be met but the install is
still failing. The issue that time was offline installation - no connection
to the gem repository. The resolution was to request temporary access to
external internet sites for my development machine. In my workplace, that
kind of access has to be approved at elevated levels, so it is not
something that can be done routinely.
I mention this in case you hear another person with install dependency
problems trying to perform offline installations. I can't explain why the
internet access is necessary, but there it is. Fortunately the force
command was successful this time (it was not successful for the previous
scenario.)

Thank you again for taking the time to respond to me.

**Comment by simi** [comment]
@JenniferMB it is really strange dev. environment, but if you have chance to download everything somewhere else and copy it to your dev. environment (having no internet access) you can try to copy your Gemfile, and use `bundle package` to download all deps and package them to folder which you can copy back later.

**Comment by JenniferMB** [comment]
Good advice, thank you!
