### ISSUE TITLE
Incorrect mime type

### ISSUE THREAD

**Issue by yupswing** [caxlsx/caxlsx#130]
Hello,
files generated by `caxlsx` have a wrong generic mime-type, while a file generated by ms excel has the correct one

```
$ file -b --mime generated-with-caxlsx.xlsx
application/octet-stream; charset=binary

$ file -b --mime generated-with-ms-excel.xlsx
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=binary
```

It looks like it was fixed in the old `axlsx` as seen in this issue which refers to a forked resolution
https://github.com/randym/axlsx/pull/528

I have no idea what was the fix but is there any way to apply the same in the `caxlsx` repo?

**Comment by kiskoza** [comment]
Hi. I checked the linked PR and all the changes are already in this repo, see the [package.rb](https://github.com/caxlsx/caxlsx/blob/faed50b162c916689afb0b91f186975b1206b31c/lib/axlsx/package.rb#L258-L259) file and [the test covering it](https://github.com/caxlsx/caxlsx/blob/faed50b162c916689afb0b91f186975b1206b31c/test/tc_package.rb#L230-L232). That means the [marcel gem](https://github.com/caxlsx/caxlsx/blob/faed50b162c916689afb0b91f186975b1206b31c/axlsx.gemspec#L22) we're using thinks it's a valid ms-excel format.

On the other hand, I checked an xlsx file generated with caxlsx and I got the same result as you. I have
```bash
> file --version
file-5.38
```

I'm trying to find how it detects office documents and see if we can improve it easily without breaking anything. Readonly mirror of `file`'s internal repo: https://github.com/file/file/tree/FILE5_38/
