### ISSUE TITLE
Version 3.1.2 or 3.2.0?

### ISSUE THREAD

**Issue by straydogstudio** [caxlsx/caxlsx#131]
Time for a new release. The border hash, auto width calculation, and chart marker improvements are really new features. I suppose that means it should be 3.2.0.

**Comment by straydogstudio** [comment]
@simi @noniq @westonganger @kiskoza @teg0474 Any thoughts on the next version number? I was thinking 3.2.0.

**Comment by straydogstudio** [comment]
Went with 3.2.0

**Comment by teg0474** [comment]
Great thanks a lot @straydogstudio

**Comment by simi** [comment]
3.2.0 is ok. :muscle: thanks for the new release!
