### ISSUE TITLE
Caxlsx monkey patches Object for all users of Caxlsx

### ISSUE THREAD

**Issue by pjskennedy** [caxlsx/caxlsx#133]
One of the reasons we've stayed away from including activesupport in our repos is to avoid the various mutation it performs on core ruby modules (`Object`, `String`, etc). It seems this gem adds a method `instance_values` to Object, while I agree this is convenient for writing ruby code in his gem, it mutates `Object` for all ruby code that use this gem at runtime.

Can we remove this monkeypatch? It seems to not come from activesupport, but rather is added manually and is easily removed.

I took a stab at removing this monkeypatch: https://github.com/caxlsx/caxlsx/pull/132

**Comment by straydogstudio** [comment]
@noniq @simi @kiskoza @randym Thoughts?

**Comment by straydogstudio** [comment]
@noniq @simi @kiskoza @randym Scratch that. I didn't see the discussion on the PR.

**Comment by straydogstudio** [comment]
PR merged
