### ISSUE TITLE
FAQ Recommendations out of date

### ISSUE THREAD

**Issue by rcuhljr** [caxlsx/caxlsx#136]
The [faq](https://github.com/caxlsx/caxlsx/wiki/FAQ#general) recommends roo as an option for reading in files, however it's become abandoned over the last two years and seems unlikely to have a new gem release to bring it up to Ruby 3+. I'm on the search for a suitable replacement and I'll leave a note here if I find one.

**Comment by rcuhljr** [comment]
My current approach is trying out https://github.com/weshatheleopard/rubyXL

**Comment by simi** [comment]
If you'll be successful feel free to ping us back. I'm not sure if you can edit the wiki page. If not, I can update the FAQ.

**Comment by rcuhljr** [comment]
I was able to replace roo with rubyXL in my application after writing a small wrapper to recreate the functionality roo had for parsing a file with columns defined by regex patterns. I have updated the FAQ, thank you!

**Comment by simi** [comment]
Nice! :handshake:

**Comment by straydogstudio** [comment]
Thanks @rcuhljr
