### ISSUE TITLE
Conditional formatting rules for blank cells aren’t compatible with Excel

### ISSUE THREAD

**Issue by skipchris** [caxlsx/caxlsx#137]
This seems almost unbelievable, but I’ve spent a long time today wrestling with it.

Adding an 'if cell is blank' rule in the most obvious way possible, i.e. 

`sheet.add_conditional_formatting 'range', { type: :containsBlanks, priority: 1, stopIfTrue: '1', type: :dxf  }`

Produces output resembling the following in the resultant xlsx:

`<cfRule type="containsBlanks" dxfId="119" priority="1" stopIfTrue="1"/>`

This looks sane, and is compatible with Google Sheets and Apple Numbers (not tested LibreOffice and friends).

If you open this file in Excel, the Conditional Formatting UI will detect this rule, and correctly show it as an “contains blanks” rule. However, the rule will not actually trigger on cells.

Looking at what Excel generates if you create a “contains blanks” rule in that UI, the output is, surprisingly:

```
    <conditionalFormatting sqref="A4:B5">
        <cfRule type="containsBlanks" dxfId="115" priority="6" stopIfTrue="1">
            <formula>LEN(TRIM(A4))=0</formula>
        </cfRule>
    </conditionalFormatting>
```

In theory I’m happy to make a pull request to fix this (I need to fix it in my project anyway!), but because it’s not 100% trivial, I thought I’d raise the issue for discussion first.

I see the code in `Axlsx::ConditionalFormattingRule` which generates the rules, it seems simple enough to edit, but because the top-left cell of the range is embedded in the rule, it looks like the range would need to be passed down from `Worksheet` to `ConditionalFormatting`. This range would be redundant for all dxf rules except `containsBlanks`, so I’d probably restructure this to (thinking out loud, not wedded to this idea…) a `ConditionalFormattingRule` and a `ContainsBlanksConditionalFormattingRule`, with a factory method in `ConditionalFormatting`.

a) Does this make sense? 
b) This is reproducible, I’m not crazy?
c) Is there a desire to see this fixed, for Excel-compatibility, even though Excel just seems to be ignoring the spec?
d) Any thoughts on my implementation suggestion if so?

**Comment by straydogstudio** [comment]
Thanks @skipchris. I agree, strange that we haven't seen this before. Are you on the Slack channel? Do you mind joining and starting the discussion in the Caxlsx channel? You should be a part of it after all. The link is on the readme page. 

In general we'd be happy for you to create a PR, even if it isn't trivial. Then we go from there. 

@noniq @simi @kiskoza Thoughts?

**Comment by simi** [comment]
If that proposed (Excel) XML is compatible with other software, I'm ok with this change.

**Comment by kiskoza** [comment]
we have a similar issue in the [Conditional formatting - text equal](https://github.com/caxlsx/caxlsx/blob/master/examples/conditional_formatting_text_equal_example.md) example. Back then we just added the formula to the example, however, this proposal looks better and we should auto-generate the formula where it's trivial

**Comment by straydogstudio** [comment]
@skipchris How are things going?

**Comment by skipchris** [comment]
Hi! I jumped into the Slack for a bit of a discussion… pick things up there? 

(I would have actually probably started already but had a crazy week, new laptop, Easter holidays etc).
