### ISSUE TITLE
Performance issue in Rails 5.2.0 and ruby 2.4.2

### ISSUE THREAD

**Issue by w3villa-amit** [caxlsx/caxlsx#146]
I am using the following gems -:
1. gem 'axlsx', git: 'https://github.com/randym/axlsx.git'
2. gem 'caxlsx_rails'
in order to generate the xlsx file  and i am facing high performance issue during the generation of the xlsx file using the `to_stream.read` function i have a simple xlsx file with 4 spread sheets and the output i am getting is taking too much time 

`Sent data SummaryReport.xlsx (0.7ms)
Completed 200 OK in 84585ms (Views: 0.6ms | ActiveRecord: 17507.6ms)`

i am getting the xlsx file creation in 84 seconds and it is a huge time.

Does anybody have any idea how i can improve the performance.

**Comment by noniq** [comment]
This is hard to analyze without looking at the actual code. You could try to temporarily skip various parts of the file generation process to narrow down the performance problem.

Anyway, this question is better suited for the [caxlsx Slack channel](https://join.slack.com/t/caxlsx/shared_invite/enQtOTI5OTM0MzI1Njk5LTBlMDQzNDk2YzkwODMxMmVkODMyYzJiZGU5NTQ3YTg5NTBlN2IwZTlmNTRjNzhiY2E0MDY2OTEyYmFlODI5NjA).
