### ISSUE TITLE
[Documentation] Add or extend the FAQ entry "migrating to caxlsx from axlsx"

### ISSUE THREAD

**Issue by rubyFeedback** [caxlsx/caxlsx#148]
Hey guys.

I recently found out that caxlsx exists; I have used axlsx to autogenerate a .xlsx file for my
gem here: https://rubygems.org/gems/studium

However had, the parts that generate the .xlsx file is quite old now, already a few years or
so. It is using axlsx.

Thus, I guess I want to move to caxlsx. I had a look at the examples and it seems as if
the API has not changed? The toplevel namespace seems to be the same. So perhaps
migrating to the new gem is simple. Either way, could you consider adding to the FAQ
(https://github.com/caxlsx/caxlsx/wiki/FAQ) the question: 

"Migrating from axlsx to caxlsx"

and specify how this goes? If nothing has to be changed then that is fine, but the FAQ
could mention it, which may help people who are scared of transitioning because things
may break. :-)  (And perhaps the API has changed in some backwards incompatible
ways, so I am really here from the point of view of a simple user of the gem.)

Thank you for reading and possibly considering!

**Comment by kiskoza** [comment]
hi @rubyFeedback , thanks for your feedback :smile:  I added a new question to the FAQ describing the situation around swapping gems from axlsx to caxlsx
