### ISSUE TITLE
API proposal change: simplify some constants to symbols, such as  Axlsx::STYLE_THIN_BORDER

### ISSUE THREAD

**Issue by rubyFeedback** [caxlsx/caxlsx#149]
Heya there,

I am going thorugh my old Axlsx specific code right now.

I noticed I was using this

    border: Axlsx::STYLE_THIN_BORDER

I tried to replace this via:

    border: :thin

That did not work.

Could such an "alias" be added for the border types at the least?

Rubygnome bindings changed this, to go away from hardcoded UPCASED constants,
to more easily usable symbols that can be used as an identifier. In this case I think
:thin or :thick may be nice to use rather than having to use the full constant name
which requires some domain-specific knowledge e. g. how it is named.

Note: this should be backwards compatible as both variants would work, so 
the Symbol is just an additional name to use the API then.

**Comment by kiskoza** [comment]
Hi. I'm not sure what you would like to change, in the [Borders Example](https://github.com/caxlsx/caxlsx/blob/master/examples/borders_example.md) we're using symbols already and not referencing upcased constants. Could you add a code snippet how are you using these constants?
