### ISSUE TITLE
[Documentation] Font Example: could it show one cell in bold?

### ISSUE THREAD

**Issue by rubyFeedback** [caxlsx/caxlsx#150]
The example here shows how to work with fonts:

https://github.com/caxlsx/caxlsx/blob/master/examples/font_example.md

Could one cell be shown in bold (that is a "fatter" font)? And perhaps another font
type too, just to show the differences for different font families in different cells
of the spreadsheet? E. g. perhaps showcase 5 cells rather than 3 as it does
right now?

By the way, great work whoever handled the screenshots. That helps
a LOT.

**Comment by kiskoza** [comment]
Hi, I think an other example describes better what you're looking for: [Custom Styles Example](https://github.com/caxlsx/caxlsx/blob/master/examples/custom_styles_example.md). The purpose of the Font Example is just to show that you can change the font family if you need to.

**Comment by noniq** [comment]
Thanks for your feedback, @rubyFeedback! As @kiskoza already mentioned, there is already a different example file regarding styling font attributes etc. However, based on your suggestions I added a third different font style, and also crosslinked the custom styling example (see 3703031e).
