### ISSUE TITLE
Mime Type for XLSX

### ISSUE THREAD

**Issue by TannerIsBender** [caxlsx/caxlsx#152]
Hello,

I'm having a hard time with emailing the .xlsx files after I create them.

Here is my code:
```
 p = Axlsx::Package.new
 p.workbook.add_worksheet(:name => "MyWorksheet") do |sheet|
     
sheet << ["", "", "",  "", "", "", ""]
sheet << []
sheet << []
sheet << ["", "", "",  "", "", "", ""]
p.use_shared_strings = true

stream = p.to_stream
File.open("tmp/test.xlsx", 'wb') { |f| f.write(stream.read) }
```
When I check the mime type it says this
➜  tmp git:(test) ✗ file --mime-type test.xlsx
test.xlsx: application/zip

MimeMagic.by_magic(File.open('tmp/test.xlsx')).type
=> "application/zip"

I can open the file locally and it works, however, when I try to email the file it gets corrupted and cannot be opened or viewed.

How can I make this file not get corrupted when I email it? I've tried setting the mime Content-Type to the following (but nothing worked):
- application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
- application/octet-stream
- application/zip

Any ideas?

**Comment by kiskoza** [comment]
We have an already merged but unreleased PR fixing the mime detection for the file command: https://github.com/caxlsx/caxlsx/pull/139

I'm not sure MimeMagic why doesn't recognize the correct mime type. We're supporting marcel's mime detection, there's a test covering it: https://github.com/caxlsx/caxlsx/blob/v3.2.0/test/tc_package.rb#L230-L233 If you have any changes in mind, feel free to open a PR

**Comment by noniq** [comment]
@TannerIsBender Have you tried with the most recent (unreleased) version? As @kiskoza mentioned, it should be fixed there.

**Comment by kiskoza** [comment]
Hi @TannerIsBender . Can you reproduce the issue with [v3.3.0](https://github.com/caxlsx/caxlsx/releases/tag/v3.3.0)?
