### ISSUE TITLE
Data validation `showDropDown` inverted behavior

### ISSUE THREAD

**Issue by neilvilela** [caxlsx/caxlsx#154]
Hello there 👋 

Yesterday I was trying to understand why a dropdown wasn't showing in a spreadsheet I'm creating and ended up understanding the `showDropDown` behavior seems to be inverted. `false` displays the dropdown, `true` hides the dropdown.

A comment was added to the documentation 10 years ago, but it doesn't explain the context:
https://github.com/caxlsx/caxlsx/commit/7ae571e152717841fdabe8eae7d1cba65ebfde4d

    # Show drop down
    # A boolean value indicating whether to display a dropdown combo box for a list type data
    # validation. Be careful: false shows the dropdown list!

Do "dropdown combo box" and just "dropdown list" have different meanings here? Or are they the same and this option is indeed bringing the opposite behavior?

**Comment by kiskoza** [comment]
hi, thanks for reporting this issue

I created two files using Excel and checked their contents. With a hidden dropdown list, the internal `sheet1.xml` file had `showDropDown="1"` in it, but with a visible dropdown list it did not contain the `showDropDown` attribute. Based on a few searches it seems to me that this is an optional attribute with default false value and `false` means show the list.

That means caxlsx only proxies over a wrongly named variable from the Excel schema. Should we mark this as known bug? I would not break existing codes using it in the "right" way.... I'm open to suggestions

**Comment by bigchickenwings** [comment]
The ideal approach IMO would be to invert the functionality, and conventionally speaking, it makes sense to be changed to `true` meaning "show the list" and keeping the variable name as `showDropDown`.

However, if that's too time-consuming, it could be interesting to just rename the variable to something like `hideDropDown` (as it wouldn't require any logical/functional changes). Many text editors (VSCode for example) allow us to select and update all occurrences of a string at once, so it should be very straightforward!

Do you think that it would make sense?

**Comment by kiskoza** [comment]
I wouldn't flip the meaning of `showDropDown` without a major version change (it can break existing codes!). Also, we cannot change how Excel works, but we can make our life easier. We can add a deprecation message or a warning to not use this as Excel's naming is misleading and add a new getter / setter named `hideDropDown` which works as expected.

If you agree, I can make a PR :+1:
