### ISSUE TITLE
How to use custom text for a hyperlink

### ISSUE THREAD

**Issue by westonganger** [caxlsx/caxlsx#160]
If we wanted to use custom text for a hyperlink how would we do that.

I see the [hyperlinks example/docs](https://github.com/caxlsx/caxlsx/blob/master/examples/hyperlink_example.md) shows some sort of custom text for the "Internal" link to the "Next Sheet" however its not obvious to me if you can do custom text for "External" links

I would be happy to help update the docs to clarify if someone can chime in here.

**Comment by westonganger** [comment]
Its also not even super clear how the internal next sheet link works. Theres nothing really indicating which sheet its pointing at, I just see cell "A1"

**Comment by noniq** [comment]
Calling `#add_hyperlink` transforms a cell into a hyperlink to the given location (internal or external), the content of the cell remains unchanged. Do you have a suggestion how we could improve the example to make it more clear?
