### ISSUE TITLE
How to use custom filename with render handler: [:axlsx]?

### ISSUE THREAD

**Issue by Justin-Shin** [caxlsx/caxlsx#161]
Hello, I am having an issue getting the right combination of things to make my output correct.

Apologies, as this is my first time raising an issue anywhere / asking for help, so if I need to fix formatting or need more information, please let me know.

I am attempting to have a link in rails that will allow the user to download an xlsx file (not inline) with the correct filename and encoding - I know that caxlsx will try to generate the right filename, I think based on the route. If the route is xls_generate_path then it becomes xls_generate.xlsx.

Currently I am generating it in the controller using a template by using `render handlers: [:axlsx], formats: [:xlsx], template: "path/template"`

This generates the excel correctly with the correct encoding as utf-8, and the resulting Content-Type is `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=utf-8`

However, I can't add the filename prop to change the filename, and attempting to do so has failed. I also tried changing the template to force a filename, which also did not work.

The next method I used was `render xlsx: "#{interpolatednamehere}", template: "path/template` and `render xlsx: "path/template", filename: "#{interpolatednamehere}`

This allows me to control the filename, but then it outputs as a text/html file for the Content-Type, at least in automated testing. When I look at the response in the browser, it changes correctly to `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;`, however it is no longer `utf-8`.

I tried to set the headers['Content-Type'] to have the charset of `utf-8` in the template, but it did not successfully do so.

My last attempt was to use the `respond_to do |format|`, but I don't think I understand that fully, as I'm not sure how that points to the right template, but even then, adding in the `response.headers['Content-Type'] = ...` as well as the `response.headers['Content-Disposition'] = 'application...` syntax provided in the README.md doesn't actually change the filename that is saved.

Is it possible for me to create a file output with a chosen filename I generate as well as preserving the charset of `utf-8`?

Thanks!

**Comment by noniq** [comment]
I think this concerns [caxlsx_rails](https://github.com/caxlsx/caxlsx_rails/), not the caxlsx gem itself.

However, in general please do not create issues for questions regarding the usage of caxlsx. You could for example [join the Caxlsx Slack channel](https://join.slack.com/t/caxlsx/shared_invite/enQtOTI5OTM0MzI1Njk5LTBlMDQzNDk2YzkwODMxMmVkODMyYzJiZGU5NTQ3YTg5NTBlN2IwZTlmNTRjNzhiY2E0MDY2OTEyYmFlODI5NjA) and ask your question there.
