### ISSUE TITLE
Feature request: move max character length to a constant

### ISSUE THREAD

**Issue by tagliala** [caxlsx/caxlsx#163]
Hi, is it possible to have `31`

https://github.com/caxlsx/caxlsx/blob/09c8f3fdd5d62918d59951697107b3b58ad24fb2/lib/axlsx/workbook/worksheet/worksheet.rb#L687

in a constant?

**Comment by noniq** [comment]
Sure! Would you like to create a pull request for it?

**Comment by tagliala** [comment]
Yes sure. I was also thinking that moving forbidden characters would be another good improvement
