### ISSUE TITLE
Have different fonts order per sheets

### ISSUE THREAD

**Issue by newfylox** [caxlsx/caxlsx#166]
Hi guys, great work by the way.

This is a question/improvement issue here.

I have two sheets in my workbook and I'm setting the first default font to my first sheet like this
```ruby
sheet_1.styles.fonts[0].name = 'Pontiac'
```
Then after I set the other first font to my second sheet like this
```ruby
sheet_2.styles.fonts[0].name = 'Arial'
```
and then I realize that my second sheet overrides the first sheet's font and none of them have their own default fonts order, it all refers to the workbook default fonts

Is it an issue? Is it normal? Is there a feature we can add to make it work?

Thanks

**Comment by westonganger** [comment]
This is as intended as per the current code

https://github.com/caxlsx/caxlsx/blob/9b6a78f43b9415bd155bddf6a6d872f5d5555595/lib/axlsx/workbook/worksheet/worksheet.rb#L643-L645

**Comment by noniq** [comment]
As @westonganger said, this is intended: There is only a single styles object in a package, this method is just a shortcut for accessing it. I added a note to the documentation to hopefully make this more clear.
