### ISSUE TITLE
Conditional  if-else rendering on .nil? for specific cells in a row 

### ISSUE THREAD

**Issue by wakatara** [caxlsx/caxlsx#181]
I have an issue where it is possible there is no tracking record for a program a report viewer wants pseudo logic of the following. How do you implement this in caxlsx (say, like you would with erb?)? I could not find any examples covering this use case. 

That is where a nil might exist on a method, do something else.

```ruby
  @programs.each do |program|
    sheet.add_row [
        program.species.name,
        program.org.name,
        program.org.country.name,
        program.assessed_for,
        # Something I thought might look like this: 
        { if program.latest_tracking_record.nil?  }
          program.program_primary_contact.full_name_and_org,
          program.program_primary_contact.email,
       { else }
          program.latest_tracking_record.tracking_primary_contact.full_name_and_org,
          program.latest_tracking_record.tracking_primary_contact.email,
       { end }
```

**Comment by kiskoza** [comment]
this is not specific to caxlsx, but you should be able to use a splat operator as the add_row expects an array

```ruby
[1, 2, *[3, 4], 5]
# => [1, 2, 3, 4, 5]

[1, 
 2, 
 *(if rand > 1
      [3, 4]
    else
      [5, 6]
    end)
]
# => either [1, 2, 3, 4] or [1, 2, 5, 6]
```

**Comment by wakatara** [comment]
Wow. I have to tell you, I have literally _never seen that before_ so was pretty impressed when it worked. Guess I need to read up on splat operators rather seriously.  8-// 

Thank you so much. Really solved a tricky logic problem converting over from using erbs previously!!

thank you!!
