### ISSUE TITLE
escape_formulas must escape all OWASP-indicated prefix characters

### ISSUE THREAD

**Issue by johnnyshields** [caxlsx/caxlsx#190]
According to [OWASP](https://owasp.org/www-community/attacks/CSV_Injection), all of the following formula-like prefixes must be escaped: `- = + @ % | \r \t`

Currently only `=` is escaped.

I will file a CVE for this issue.

**Comment by noniq** [comment]
I’m not sure if this is the right thing to do. The OWASP article is about “**CSV** injection”, but we’re not generating a CSV file.

In fact it seems that this change as it was implemented in #186 had the opposite effect: Cells containing text beginning with `@` (for example) are now generated as formula nodes. Here’s a minimal test script to reproduce the issue:

```ruby 
require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "caxlsx", "3.3.0"
end
ws = Axlsx::Package.new.workbook.add_worksheet
ws.add_row ['@SUM(A1)', '=SUM(A1)']
puts ws.rows.last.to_xml_string(0)
```

This was the output generated by caxlsx 3.3.0:

```xml
<row r="1">
  <c r="A1" s="0" t="inlineStr">
    <is>
      <t>@SUM(A1)</t>
    </is>
  </c>
  <c r="B1" s="0" t="str">
    <f>SUM(A1)</f>
  </c>
</row>
```

If you change the version to 3.4.0 the output now looks like this:

```xml
<row r="1">
  <c r="A1" s="0" t="str">
    <f>@SUM(A1)</f>
  </c>
  <c r="B1" s="0" t="str">
    <f>SUM(A1)</f>
  </c>
</row>
```

Note that in 3.3.0 the cell containing `@SUM(A1)` is a text cell (`<t>…</t>`), while in 3.4.0 it is a formula (`<f>…</f>`). It’s not a *valid* formula for Excel though, and this is why people see errors like #207 and #208.

I think we should revert 98a26ea04e886ce6f712e4e97e6b9d09b4691bb6. (On the other hand, having `FORMULA_PREFIXES` as an explicit constant is a nice refactoring – maybe keep it and just change it to contain `'='` only, to restore the old behaviour?)

**Comment by kiskoza** [comment]
In some cases you can start a formula with an `@` sign, at least I am able to manually type in `@sum(A1:B1)` and excel handles it. Not sure though how it stores this formula, need to investigate later.

Then I googled a bit and found this: https://superuser.com/questions/1471013/in-the-beginning-of-a-formula

I think we should consider supporting `@` formulas in 4.x when we explicitly need to mark cells as formulas - I agree with the patch reverting some of the changes in 3.x versions

**Comment by johnnyshields** [comment]
@kiskoza it looks like these @ formulas still come after an = sign

**Comment by noniq** [comment]
Ah right, `=@SUM(A1)` seems indeed to be a valid Excel formula. And it is serialized as `<f>@SUM(A1)</f>` (because the serialization always strips the `=` at the front: `=SUM(B1)` is serialized as `<f>SUM(B1)</f> etc.).

However, I still think we should only interpret something as a formula if it starts with `=`:

```ruby
add_row ['@SUM(A1)`] # => never a formula, regardless of the value of `escape_formulas`
add_row ['=@SUM(A1)`], escape_formulas: true # => not a formula either
add_row ['=@SUM(A1)`], escape_formulas: false # => a formula
```

In fact, in my understanding, this is exactly how it worked up until 3.3.0; and #209 seems to successfully restore this behaviour.

**Comment by johnnyshields** [comment]
This can now be closed.
