### ISSUE TITLE
Please consider to revert (or reimplement) parts of #177

### ISSUE THREAD

**Issue by tagliala** [caxlsx/caxlsx#201]
- The feature broke compatibility with Ruby 2.3 and 2.4
- Tests are performing a real network connection to `via.placeholder.com`

```
Error: test_to_xml_has_correct_r_id(TestPic): SocketError: Failed to open TCP connection to via.placeholder.com:443 (getaddrinfo: nodename nor servname provided, or not known)
```

Please also consider to disable network connection in specs to prevent this in the future. I also suggest to use `example` domains to prevent abuse and information disclosure

/cc @kiskoza

**Comment by kiskoza** [comment]
I'm trying to address this in https://github.com/caxlsx/caxlsx/pull/202 . I found the issue with Ruby 2.3 and 2.4 already, next I'm going to look into mocking out the network requests for these test
