### ISSUE TITLE
image example does not work.

### ISSUE THREAD

**Issue by naro143** [caxlsx/caxlsx#206]
The remote image example is not working.
https://github.com/caxlsx/caxlsx/blob/master/examples/image_example.md

▼error message
https://learn.microsoft.com/en-us/outlook/troubleshoot/message-body/the-linked-image-cannot-be-displayed-error

ruby: 3.1.0
caxlsx: 3.4.0

**Comment by tagliala** [comment]
Hi,

I can't replicate

<img width="374" alt="image" src="https://user-images.githubusercontent.com/556268/232445780-3e15ee01-7ede-46e7-8877-345b703d9a54.png">

Example:

```
3.1.3 :001 > RUBY_VERSION
 => "3.1.3" 
3.1.3 :002 > system 'git describe --tags'
v3.4.0
 => true 
3.1.3 :003 > require 'axlsx'
 => true 
3.1.3 :004 > Axlsx::VERSION
 => "3.4.0" 
3.1.3 :005 > require 'axlsx'

p = Axlsx::Package.new
wb = p.workbook

# image = File.expand_path('assets/image1.jpeg')

wb.add_worksheet(name: 'Image') do |sheet|
  # sheet.add_image(image_src: image, start_at: 'B2', width: 100, height: 100)
  # sheet.add_image(image_src: image, start_at: 'E1', end_at: 'G3')
  sheet.add_image(image_src: 'https://via.placeholder.com/150.png', remote: true, start_at: 'E4', end_at: 'G6')
end

p.serialize 'image_example.xlsx'
 => true 
```

**Comment by naro143** [comment]
Thank you very much.

I tried it this morning and it worked.
It seems it was a network issue.
I will close it.

**Comment by khanhpt-2853** [comment]
@tagliala is this work for version 3.3.0
```
3.1.3 :004 > Axlsx::VERSION
 => "3.3.0" 
```

**Comment by tagliala** [comment]
Remote images have been introduced in 3.4.0, please upgrade

**Comment by khanhpt-2853** [comment]
@tagliala It's working, thank you

**Comment by oriolblanc** [comment]
I'm using version 3.4.1, and I'm not able to make remote images work. 

Pasting this same example and opening is empty. Any clue?

``` require 'axlsx'

p = Axlsx::Package.new
wb = p.workbook

# image = File.expand_path('assets/image1.jpeg')

wb.add_worksheet(name: 'Image') do |sheet|
  # sheet.add_image(image_src: image, start_at: 'B2', width: 100, height: 100)
  # sheet.add_image(image_src: image, start_at: 'E1', end_at: 'G3')
  sheet.add_image(image_src: 'https://via.placeholder.com/150.png', remote: true, start_at: 'E4', end_at: 'G6')
end

p.serialize 'image_example.xlsx'
```

**Comment by oriolblanc** [comment]
It works in Microsoft Excel, but it's not working on Google Spreadsheet. Is it intended, or am I doing something wrong? Any clue?

**Comment by kiskoza** [comment]
this is a known issue, it's even in the readme. feel free to open a new issue about it and make some investigations

> 2. Google Docs
>     * Images are known to not work with google docs
