### ISSUE TITLE
3.4.0 breaking change

### ISSUE THREAD

**Issue by datanoise** [caxlsx/caxlsx#208]
I am not using any formulas in my excel files, but after upgrading to ver 3.4.0 Excel complains that it has to repair documents. After repairing it generates a message suggesting that it removed some formulas in the document.

**Comment by johnnyshields** [comment]
Sorry for that. Fix is here: https://github.com/caxlsx/caxlsx/pull/209

**Comment by noniq** [comment]
Fixed in 3.4.1 (which has just been released). Thanks for your report!
