### ISSUE TITLE
Choose either appveyor.yml or travis.yml

### ISSUE THREAD

**Issue by westonganger** [caxlsx/caxlsx#22]
I see that we have two CI files, `appveyor.yml` and `travis.yml`

It appears travis.yml is most up to date. We should delete `appveyor.yml` if we are not using it.

**Comment by noniq** [comment]
Seems to make sense. @straydogstudio, as you recently updated `travis.yml` – is there any reason you see why we should keep `appveyor.yml`?

**Comment by straydogstudio** [comment]
I guess it depends on if we want to test Windows ruby versions. I've not gone through the trouble of setting it up.

**Comment by straydogstudio** [comment]
I notice it was added in 2016 and wasn't changed until we created caxlsx.

**Comment by straydogstudio** [comment]
Travis CI opened up windows testing a year ago (https://blog.travis-ci.com/2018-10-11-windows-early-release). We can remove the file.
