### ISSUE TITLE
outline_level_rows err

### ISSUE THREAD

**Issue by vortx** [caxlsx/caxlsx#24]
Hello! I make the filter "outline_level_rows", everything works well - except for the display (+) it does not work correctly, it stands in the (-) position, this is not the problem of "sheet_pr.outline_pr.summary_below"! examine the image ...
![err](https://user-images.githubusercontent.com/5041966/67847469-95537f00-fb0b-11e9-9a6c-c04332ff59eb.png)
row - 1...13 ок !
row - 3...5 ERR there should be +
row - 7...8 ERR there should be +

**Comment by noniq** [comment]
Thanks for the report.

As a general notice, I’m not sure if anyone of the maintainers (me included) has the resources to  triage issues like this. On the other hand I’d like to prevent a situation where there are 100+ open issues and nobody really knows which of them are real bugs or usage errors or feature requests or something else entirely.

So I propose creating a label “needs triage” that we can apply to these issues. We should also a “How to participate” (or similar) section in the readme, mentioning that a great way to support the project is to help with triaging these issues.

@jurriaan @OpenCoderX @simi @straydogstudio What do you think?

**Comment by vortx** [comment]
I understand everything, but I'm still not very good here. I found what’s the reason but don’t know where to fix it in gem.
This is what should be in XML, so that he can put 
<row r="3" outlineLevel="1" **collapsed="1"** spans="1:4">

**Comment by straydogstudio** [comment]
@noniq I agree. Let's create a tag for triage.

**Comment by noniq** [comment]
@vortx Thanks again for your report! Could you help in narrowing down this issue even further? I’m especially referring to the last two items mentioned in the [contribution guidelines](https://github.com/caxlsx/caxlsx/blob/master/CONTRIBUTING.md#helping-to-resolve-existing-issues):

 * Is it clear which portion of the caxlsx code is causing the issue? If not, try to determine the relevant code.
 * How did the relevant code came into the state causing the issue? Has it been there since the beginning, or is it the result of some later change?

**Comment by vortx** [comment]
- as I understand it, this is the part of the code that is responsible for this, and in my fork I fixed it, this solved the problem with level 2 but level 1 remained with an error.
lib/axlsx/workbook/worksheet/worksheet.rb

- this error occurs immediately

**Comment by noniq** [comment]
If you’ve already fixed it in your fork, could you provide a pull request?

**Comment by vortx** [comment]
as soon as I’m completely sure that I fixed it, I’ll immediately make a request. As I said, I managed to defeat all levels except the 1st

**Comment by OpenCoderX** [comment]
@vortx Can you post the complete example code, I can take this one.

**Comment by vortx** [comment]
@OpenCoderX  At the moment, I managed to make sure that all levels except the 1st are correctly displayed. You can look in my fork.
[https://github.com/caxlsx/caxlsx/blob/master/lib/axlsx/workbook/worksheet/worksheet.rb](url)
line: 647

**Comment by OpenCoderX** [comment]
Ok great, I would still be interested to see the sample code that reproduces the error with level 1.

**Comment by vortx** [comment]
@OpenCoderX to get this error change all attachments to true or only 1st level

**Comment by OpenCoderX** [comment]
@vortx When I run this code:
```
require 'caxlsx'

Axlsx::Package.new do |package|
  package.workbook.add_worksheet(name: 'outline_error') do |worksheet|
    worksheet.add_row [1, 2, 3, 4]
    worksheet.add_row [2, 3, 4, 5]
    worksheet.add_row [3, 4, 5, 6]
    worksheet.add_row [4]
    worksheet.add_row [5]
    worksheet.add_row [6]
    worksheet.add_row [7]
    worksheet.add_row [8]
    worksheet.add_row [9]
    worksheet.add_row [10]
    worksheet.add_row [11]
    worksheet.add_row [12]
    worksheet.add_row [13]
    worksheet.add_row [14]
    worksheet.sheet_pr.outline_pr.summary_below = false
    worksheet.outline_level_rows 1, 13, 1, false
    worksheet.outline_level_rows 3, 5, 2, true
    worksheet.outline_level_rows 7, 8, 2, true
  end
  package.serialize("output/outline_error_#{rand(100)}.xlsx")
end
```
I get this result:
![image](https://user-images.githubusercontent.com/727104/68622585-7906f900-04a0-11ea-885e-f259f2df2256.png)

**Comment by vortx** [comment]
@OpenCoderX  
I tested on Ubuntu-18 LibreOffice and the WPS office. And also Windows -7 Office -7 and 10. 
I’ll definitely check this on a newer version of the office 13-16 in the language and report the results

**Comment by OpenCoderX** [comment]
When I test with LIbreoffice on 18.04 I get the same result. Seems like the initial state is incorrect but after clicking the '-' it resets and operates correctly.
![image](https://user-images.githubusercontent.com/727104/68656456-da11e980-04ff-11ea-9e68-9b4be1b81182.png)

**Comment by OpenCoderX** [comment]
The open office xml standard is found here, [ECMA-376](https://www.ecma-international.org/publications/standards/Ecma-376.htm)

When I look at the xml schema they provide:
```

C:\Users\OpenCoderX\Desktop\openxml\xml_schema\sml.xsd:
 2228      <xsd:attribute name="thickTop" type="xsd:boolean" use="optional" default="false"/>
 2229      <xsd:attribute name="thickBottom" type="xsd:boolean" use="optional" default="false"/>
 2230:     <xsd:attribute name="outlineLevelRow" type="xsd:unsignedByte" use="optional" default="0"/>
 2231:     <xsd:attribute name="outlineLevelCol" type="xsd:unsignedByte" use="optional" default="0"/>
 2232    </xsd:complexType>
 2233    <xsd:complexType name="CT_Cols">
 ....
 2245      <xsd:attribute name="customWidth" type="xsd:boolean" use="optional" default="false"/>
 2246      <xsd:attribute name="phonetic" type="xsd:boolean" use="optional" default="false"/>
 2247:     <xsd:attribute name="outlineLevel" type="xsd:unsignedByte" use="optional" default="0"/>
 2248      <xsd:attribute name="collapsed" type="xsd:boolean" use="optional" default="false"/>
 2249    </xsd:complexType>
 ....
 2266      <xsd:attribute name="hidden" type="xsd:boolean" use="optional" default="false"/>
 2267      <xsd:attribute name="customHeight" type="xsd:boolean" use="optional" default="false"/>
 2268:     <xsd:attribute name="outlineLevel" type="xsd:unsignedByte" use="optional" default="0"/>
 2269      <xsd:attribute name="collapsed" type="xsd:boolean" use="optional" default="false"/>
 2270      <xsd:attribute name="thickTop" type="xsd:boolean" use="optional" default="false"/>

4 matches in 1 file


Searching 26 files for "collapsed"

C:\Users\OpenCoderX\Desktop\openxml\xml_schema\sml.xsd:
 1655      <xsd:attribute name="outline" type="xsd:boolean" default="true"/>
 1656      <xsd:attribute name="offset" type="ST_Ref"/>
 1657:     <xsd:attribute name="collapsedLevelsAreSubtotals" type="xsd:boolean" default="false"/>
 1658      <xsd:attribute name="axis" type="ST_Axis" use="optional"/>
 1659      <xsd:attribute name="fieldPosition" type="xsd:unsignedInt" use="optional"/>
 ....
 2246      <xsd:attribute name="phonetic" type="xsd:boolean" use="optional" default="false"/>
 2247      <xsd:attribute name="outlineLevel" type="xsd:unsignedByte" use="optional" default="0"/>
 2248:     <xsd:attribute name="collapsed" type="xsd:boolean" use="optional" default="false"/>
 2249    </xsd:complexType>
 2250    <xsd:simpleType name="ST_CellSpan">
 ....
 2267      <xsd:attribute name="customHeight" type="xsd:boolean" use="optional" default="false"/>
 2268      <xsd:attribute name="outlineLevel" type="xsd:unsignedByte" use="optional" default="0"/>
 2269:     <xsd:attribute name="collapsed" type="xsd:boolean" use="optional" default="false"/>
 2270      <xsd:attribute name="thickTop" type="xsd:boolean" use="optional" default="false"/>
 2271      <xsd:attribute name="thickBot" type="xsd:boolean" use="optional" default="false"/>

3 matches in 1 file

```
the `collapsed` property is boolean and should output as 'true' or 'false'

**Comment by vortx** [comment]
@OpenCoderX 
You continue to look in the Windows system, meanwhile I look in both the Windows and Linux system. Look how he builds a sheet
