### ISSUE TITLE
Date Data Validation not working

### ISSUE THREAD

**Issue by aaldrich** [caxlsx/caxlsx#26]
When using the sheet.add_data_validation method with a type of :date I get the following error:

ArgumentError: Invalid Data: date. data_validation_type must be one of [:custom, :data, :decimal, :list, :none, :textLength, :time, :whole].

**Comment by vortx** [comment]
@aaldrich hi, send your piece of code

**Comment by straydogstudio** [comment]
Fixed and released in 3.0.4
