### ISSUE TITLE
Extrange behaviour referencing cells in other sheets

### ISSUE THREAD

**Issue by nicalejo** [caxlsx/caxlsx#27]
I have generated a xlsx with a first sheet named _1T_ and a second one referencing it in one of its cells. The value I am trying to set in the cell is _=Q8+$1T.Q9_ but once open the xlsx the value is _=Q8+$1t.q9_ with _t_ and _q_  lower case and the reference does not work

The code is like this

**sheet.add_row [nil,nil, "Accumulated", 
                  "=Q" + (expenses.length + 5).to_s + "+$1T.Q" + (@expenses1T.length + 6).to_s
                  ]**

**Comment by noniq** [comment]
Sounds like a bug, indeed. Could you try identifying the relevant code and provide tests and a patch?

**Comment by newfylox** [comment]
Has anybody fixed this? I'm having this bug today as well!

**Comment by newfylox** [comment]
It's working! Instead of `"=$Sheet_1.Q9"` it should be `"=Sheet_1!Q9"` and Excel will convert it to `"=$Sheet_1.Q9"`

**Comment by noniq** [comment]
So if I understand correctly this issue is about how to correctly type references to cells in other sheets in a formula? I think Excel has always used the `Sheetname!Cell` syntax, are `Sheetname.Cell` something that’s used in other apps?

**Comment by newfylox** [comment]
When you open a sheet that is already referencing another sheet cell, its value is `=Sheetname.Cell`, and so when we try this formula in a real Excel, it's working! But if you try this formula in this Gem, it doesn't because it downcases letters. As you said, the real syntax is `Sheetname!Cell`.

**Comment by noniq** [comment]
Which version of Excel are you using? At least Excel 365 for macOS (16.64) is still showing the syntax with a `!`:

<img width="612" alt="grafik" src="https://user-images.githubusercontent.com/244158/190408427-be616036-4f85-46c8-9b57-b565c848fa50.png">

**Comment by newfylox** [comment]
Now I got it. I'm using LibreOffice 7.3.5.2. It will read correctly the `!` syntax of Excel and use its own `$sheet.A1` syntax. My bad! Not all those details are different from one to another but this one is!

**Comment by noniq** [comment]
Thanks for your feedback. I’ll see if we can add this to the FAQ to avoid future confusion. 😃

**Comment by newfylox** [comment]
Thanks!
