### ISSUE TITLE
Did #227 introduce a memory leak?

### ISSUE THREAD

**Issue by tagliala** [caxlsx/caxlsx#272]
Hi, I've noticed a huge increase of retained objects and I've bisected to 57865b2.

Since I'm not an expert of this kind of issues, maybe it is normal for the memory profiler. I'm using a slightly modified version of `profile_memory` without the `shuffle`

### Before (3b9ac17)
```
Total allocated: 103045564 bytes (1634154 objects)
Total retained:  272 bytes (3 objects)
```

### Leak started? (4627bcc and 71b358f)

```
Total allocated: 86643076 bytes (1224133 objects)
Total retained:  2000 bytes (24 objects)
```

### After (57865b2)

```
Total allocated: 79101844 bytes (1024132 objects)
Total retained:  860848 bytes (10025 objects)
```

@pkmiec could you please take a look or help me understanding those metrics?

Ref: #227

**Comment by pkmiec** [comment]
You are correct. That change favors lower allocated memory over higher retained memory. I think there is a way to fix it such that we no additional retained memory while still have lower allocated memory. Stay tuned.

**Comment by kiskoza** [comment]
I think we're in a good shape now regarding memory, no leaks as far as I know. Feel free to re-open this ticket if you have more ideas, improvements or concerns.
