### ISSUE TITLE
Latest axlsx (2.1.0.pre) requires rubyzip (~> 1.1.7)

### ISSUE THREAD

**Issue by DimitriOstapenko** [caxlsx/caxlsx#301]
Incompatible with latest rubyzip version. 
Critical vulnerability in prior versions of rubyzip cannot be addressed as a result

Dependabot cannot update rubyzip to a non-vulnerable version
The latest possible version that can be installed is 1.1.7 because of the following conflicting dependency:

axlsx (2.1.0.pre) requires rubyzip (~> 1.1.7)
The earliest fixed version is 1.3.0.

**Comment by tagliala** [comment]
Hi,

the latest released version of `caxlsx` is 3.4.1

`axlsx` is the discontinued version hosted at https://github.com/randym/axlsx, which is not maintained anymore

Please change your Gemfile and replace `gem 'axlsx'` with `gem 'caxlsx'`

**Comment by DimitriOstapenko** [comment]
Hi,

Great, thank you so much! I hope they are fully compatible

--
Dmitri Ostapenko
APD OMS
Site administrator
***@***.***
