### ISSUE TITLE
A proposal for some more API flexibility for the future

### ISSUE THREAD

**Issue by rubyFeedback** [caxlsx/caxlsx#33]
Hello there,

I tried to reformat a cell via:

    sheet.rows.last.cells[1].border = { :style => :thick, :color =>'FF0000FF' }

This fails via:

    generate_spreadsheet.rb:209:in `block (3 levels) in run': undefined method
    `border=' for #<Axlsx::Cell:0x0000000004c2b3a8> (NoMethodError)

Ok, no such method exist - bear with me as I only recently started to dig into
caxlsx so lots of things won't work for me. :)

My primary question is:

Would it be useful to consider adding such methods? Such as .border = or
similar methods. Some methods already exist, such as:

    sheet.rows.last.cells[1].shadow = true
    sheet.rows.last.cells[2].sz = 20

Ruby-gtk also has support for something like:

    widget.border_width = 10
    widget.set_border_width(5)

For caxlsx I also tried:

    sheet.rows.last.cells[1].border_width = 10

But no such method exists.

I am not sure how strict and stringent the policy is for the project here, but it may be useful
to add more flexibility in regards to how people could use the project. I assume that th
above is currently possible, as-is, but it requires one to define this through a style (I
think), whereas I think adding this additionally might be useful in general to downstream
users of the project.  Internally ruby-gtk keeps an option hashes and updates that,
so the missing code could perhaps be mapped from the functionality to however
caxlsx is solving this internally. (I am not yet at the stage where I will dig into the
source; right now I am working through the examples and picking what seems 
useful. I started that way with ruby-gtk too. It's a slow process but it sort of works
for me)

Thanks for reading.

**Comment by noniq** [comment]
Sounds promising! You’re right in that it needs to be done via style definitions. If it’s possible to implement this feature without adding too much complexity in general, it would be a welcome addition.

**Comment by westonganger** [comment]
@rubyFeedback consider using [`axlsx_styler`](https://github.com/axlsx-styler-gem/axlsx_styler)

Kind of off subject but, Its almost debatable that this gems code should be merged in to caxlsx core. Pretty much necessary functionality for advanced styling.

**Comment by noniq** [comment]
Thanks @westonganger, didn’t know about that gem! I added references to it in the README and the FAQ.

About merging that gem: I’d say let’s keep it seperate as long as it works and is actively maintained :-)
