### ISSUE TITLE
Crashing chart caused by its title

### ISSUE THREAD

**Issue by kiskoza** [caxlsx/caxlsx#37]
I tried to create a chart with an `&` symbol in its name. When I opened it, it tried to recover the worksheet, said `Removed Part: /xl/drawings/drawing1.xml part.  (Drawing shape)` and got rid of the chart.

I know that xlsx is just a bunch of xml zipped into one file and `&` char has special meaning there. However, I haven't got an error for normal cells, https://github.com/randym/axlsx/issues/68 solved it already. Based on that ticket if I use the html escaped character (`&amp;`), it works fine.

My suggestion is to use the same string escape code for charts. 

Here is a sample code to reproduce the error with `v3.0.1`

```ruby
[
  { filename: 'sample', title: 'A and B' }, # Sample charrt, works fine
  { filename: 'failing', title: 'A & B' }, # Failing chart
  { filename: 'working', title: 'A &amp; B' }, # Working, but ugly solution
].each do |data|
  package = Axlsx::Package.new
  workbook = package.workbook
  sheet = workbook.add_worksheet(name: 'Chart Test')

  sheet.add_row ['&'] # Works with normal cells every time

  sheet.add_chart(Axlsx::BarChart, title: data[:title]) do |chart|
    chart.add_series data: [3, 7], labels: ['A', 'B'], title: data[:title]
  end

  package.serialize("#{data[:filename]}.xlsx")
end
```

As far as I know the required code is in [rich_text_run.rb](https://github.com/caxlsx/caxlsx/blob/master/lib/axlsx/workbook/worksheet/rich_text_run.rb#L207), we need to apply the same for charts.

**Comment by noniq** [comment]
Thanks for this exceptionally well researched bug report!

Would you like to open a PR with a fix?
