### ISSUE TITLE
Is there a way to print a single sheet

### ISSUE THREAD

**Issue by newfylox** [caxlsx/caxlsx#373]
I was wondering if it's possible to show a single sheet when generating the file to xlsx format?

Like I have 2 sheets (the second one is for calculating) but would like to only output the first sheet.

Thanks

**Comment by kiskoza** [comment]
Are you looking for [Hide Sheet Example](https://github.com/caxlsx/caxlsx/blob/master/examples/hide_sheet_example.md)?

**Comment by kiskoza** [comment]
Based on the thumbsup emoji on my previous comment, it seems to me the solution was found. I'm closing this issue, but feel free to re-open it with new informations if neccessary.
