### ISSUE TITLE
Create Slack Channel

### ISSUE THREAD

**Issue by straydogstudio** [caxlsx/caxlsx#38]
Should we drop the IRC / Twitter / Google Group references and create a community Caxlsx Slack channel?

**Comment by noniq** [comment]
Good idea! This will also make communicating about maintenance, releases etc. easier.

**Comment by straydogstudio** [comment]
Added slack channel subscription links to each readme.

**Comment by straydogstudio** [comment]
@noniq @simi @jurriaan @OpenCoderX People are starting to join the Slack channel. There are no questions yet, but I believe I am the only one on each day. Please consider joining. I will give all of you admin access. 

https://join.slack.com/t/caxlsx/shared_invite/enQtOTI5OTM0MzI1Njk5LTBlMDQzNDk2YzkwODMxMmVkODMyYzJiZGU5NTQ3YTg5NTBlN2IwZTlmNTRjNzhiY2E0MDY2OTEyYmFlODI5NjA
