### ISSUE TITLE
Ruby 3.4 warning: URI::RFC3986_PARSER.make_regexp is obsoleted. Use URI::RFC2396_PARSER.make_regexp explicitly

### ISSUE THREAD

**Issue by tagliala** [caxlsx/caxlsx#397]
```
/home/runner/work/caxlsx/caxlsx/lib/axlsx/drawing/pic.rb:83: warning: URI::RFC3986_PARSER.make_regexp is obsoleted. Use URI::RFC2396_PARSER.make_regexp explicitly.
```

Refs:
- https://github.com/ruby/uri/pull/114
- ruby/uri#118
- rails/rails#52682

**Comment by kiskoza** [comment]
I wasn.t sure at first where should I find these, but I can see the warnings with ruby-head (we should fix this for a less noisy ruby 3.4)
