### ISSUE TITLE
Restructure examples folder

### ISSUE THREAD

**Issue by kiskoza** [caxlsx/caxlsx#46]
There are a lot of snippets in the examples/example.rb (in a hardly readable format). Some of the examples are in separate files (I guess it was easier to create a new file than follow the pattern in the examples.rb). The comments around the snippets not always tell you what it really does, etc. We need to clean up these files to be more helpful.

There are ongoig threads about this topic:
* #32 Pointing out that some of the files are a bit outdated
* #41 Solving the previouos issue with some suggestions
* https://github.com/caxlsx/caxlsx/pull/34#issuecomment-567679024 Describing how we usually want to use the examples during gem development

Based on the above we want to achieve these goals:
- [ ] Unified code samples (easy to understand and spot the difference when they look the same)
- [ ] Descriptive examples (descriptions and / or images how the output looks like)
- [ ] Discoverable examples (categories or easily searchable lists)
- [ ] Separate files (hard to find anything useful in the big example.rb)
- [ ] Runnable examples (for manual testing)

**Comment by kiskoza** [comment]
Implementation idea from https://github.com/caxlsx/caxlsx/pull/41#issuecomment-569425063 : Use the wiki for the examples.

Pros:
* Descriptive
* Discoverable

Cons:
* Hard to run
* Need to maintain codes in two repos (main repo + wiki)

**Comment by noniq** [comment]
I‘m slightly biased against transferring the examples to Wiki, for the cons mentioned by @kiskoza. 

My favourite solution would be (I think) to have consistently structured and well documented examples as part of the repo itself. 

But again, this is only a very slight preference – I’d be happy about any improvement of the status quo. 😇

**Comment by kiskoza** [comment]
I'm still working on it - I hope I'll be able to finish it soon

**Comment by kiskoza** [comment]
I've got 3 .rb files remaining in the examples folder that I need to transform into .md, then I need to fix some tests (I moved some of the example images and the specs need them) - a bit closer to the end, but still in progress

**Comment by noniq** [comment]
FIxed by #47.
