### ISSUE TITLE
Tags for past releases

### ISSUE THREAD

**Issue by swatosh** [caxlsx/caxlsx#5]
If it isn't terribly difficult, it'd be nice to see tags for past (and future!) releases that are available on rubygems of caxlsx:
3.0.0

and axlsx:
3.0.0.pre
2.1.0.pre
2.0.1

Or, maybe pointers to where I'm missing them? Thanks!

**Comment by OpenCoderX** [comment]
You are correct, they are missing from the github repo, I'm going to create them, I just need to figure how how to map releases from rubygems to commits. They will be created soon. Thanks for your patience, the axlsx gems were recently moved to a new org and we are still gathering our bearings.

**Comment by swatosh** [comment]
That would be awesome! Thanks for looking into it.

**Comment by vizcay** [comment]
Tag for 3.0.0.pre still missing for example.

**Comment by OpenCoderX** [comment]
I have created tags for 3.0.0.pre, 3.0.0 and 3.0.1. I do not find the exact commit used to push version 2.0.2 up to rubygems so I elected not to guess, we want users to upgrade to the 3.0 series and report any issues found there so, unless someone can let me know which commit to use when I generate the 2.0.2 release it will remain missing. 

It looks like there have been some great doc updates that will be included in the 3.0.2 release, thanks for that @noniq and @westonganger. I'll watch for that release and push the tag or if whoever cuts 3.0.2 (which seems like an appropriate version, I see a bug fixe(thanks @alimujtaba) but no api changes) can do the following to create and push the tag:
```
git checkout *commit used to create version 3.0.2*
git tag -a v3.0.2 -m 'version 3.0.2'
git push origin v3.0.2
```
Note: please take care to audit your local `git config user.name` and `git config user.email` settings to ensure they match the account that has been granted caxlsx org maintainer access. When I first pushed these new tags I did not audit those settings and mistakenly created the tags with an account I use for a different project. You want the user.name and user.email to match the primary email and user name associated with your caxlsx maintainer account.

**Comment by swatosh** [comment]
Cool! Thank you!

**Comment by OpenCoderX** [comment]
I'll close this issue now, please feel free to open a new one if needed.
