### ISSUE TITLE
explosion for pie chart throwing error

### ISSUE THREAD

**Issue by jenn-t** [caxlsx/caxlsx#58]
Hello! Having an issue trying to add an explosion to my pie chart. I'm using Ruby 2.6.6 and caxlsx (3.0.2) on Windows 10. The error is thrown when `.add_series` is called. If you run it without the `:explosion => 1` bit, it works beautifully. 

Here is my code: 

    require 'rubygems'
    require 'caxlsx'
    
    # using ruby 2.6.6, caxlsx 3.0.2
    
    @package = Axlsx::Package.new
    @work_book = @package.workbook
    
    sheet = @work_book.add_worksheet(:name => "explosions")
    sheet.add_row(['fruit', 'value'])
    raw_data = {:apple => 35, :orange => 11, :grape => 14, :strawberry => 11}
    raw_data.each { |key, value| sheet.add_row([key.to_s.tr(':', ''), value.to_s]) }
    
    start_coords = [3, 1]
    end_coords = [11, 20]
    labels = {:start=>"A2", :end=>"A5"}
    data = {:start=>"B2", :end=>"B5"}
    colors = ["92CDDC", "B1A0C7", "DA9694", "C4D79B"]
    
    sheet.add_chart(Axlsx::Pie3DChart, :start_at => start_coords, :end_at => end_coords, :title => 'fruit', :rot_x => 90, :show_legend => false) do |pie_chart|
    
     # with the :explosion at the end, it blows up here (pun totally intended), without the :explosion it works beautifully
     pie_chart.add_series :labels => sheet["#{labels[:start]}:#{labels[:end]}"], :data => sheet["#{data[:start]}:#{data[:end]}"], :colors => colors, :explosion => 1
    
      pie_chart.d_lbls.show_percent = true
      pie_chart.d_lbls.d_lbl_pos = :outEnd
      pie_chart.d_lbls.show_leader_lines = true
     pie_chart.d_lbls.show_cat_name = true
    end

    @package.serialize("explosions_pls.xlsx")

Here is the error: 

    Traceback (most recent call last):
            16: from C:/casnc/repos/play_area/ruby_stuff/explosions.rb:31:in `<main>'
            15: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/package.rb:97:in `serialize'
            14: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/output_stream.rb:54:in `open'
            13: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/package.rb:98:in `block in serialize'
            12: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/package.rb:160:in `write_parts'
            11: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/package.rb:160:in `each'
            10: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/package.rb:163:in `block in write_parts'
             9: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/pie_3D_chart.rb:37:in `to_xml_string'
             8: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/chart.rb:200:in `to_xml_string'
             7: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/pie_3D_chart.rb:40:in `block in to_xml_string'
             6: from (eval):3:in `each'
             5: from (eval):3:in `each'
             4: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/pie_3D_chart.rb:40:in `block (2 levels) in to_xml_string'
             3: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/pie_series.rb:49:in `to_xml_string'
             2: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/series.rb:65:in `to_xml_string'
             1: from C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/pie_series.rb:50:in `block in to_xml_string'
    C:/casnc/Ruby26-x64/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.2/lib/axlsx/drawing/pie_series.rb:50:in `+': no implicit conversion of Integer into String (TypeError)

Thanks so much! Let me know if you need anything else - happy to help!

**Comment by straydogstudio** [comment]
Note: line 50 in lib/axlsx/drawing/pie_series.rb is not converting `@explosion` to a string before inclusion into the output. Possibly worth adding a test, even if it can't check if the output is correct.

**Comment by straydogstudio** [comment]
So this ought to throw an error: https://github.com/caxlsx/caxlsx/blob/master/test/drawing/tc_pie_series.rb#L26

@noniq Do you know if the tests are in a random order? Are they sequential?

**Comment by straydogstudio** [comment]
Test adjusted, fixed, and committed. @jenn-t You can use the github repo to get a working version.

@noniq Should we release a gem for this? Or let it wait for the next release? It was apparently broken for 7 years. Obviously not used much.

**Comment by noniq** [comment]
There have been quite a few changes / fixes since the last release, so let's go for it!

(Having that said, maybe we should wait for #57 and include it also?)

**Comment by straydogstudio** [comment]
@noniq I think we should wait for #57. We are waiting for a test?
