### ISSUE TITLE
Ask Github to change caxlsx (and other forked caxlsx gems) to a normal repo

### ISSUE THREAD

**Issue by straydogstudio** [caxlsx/caxlsx#59]
Because caxlsx is forked from axlsx you cannot search the code on Github. There are probably other consequences, but I do not know them. Searching the repo is useful. We are not likely to ever pull code back into axlsx. Should we ask Github to change caxlsx into a normal repository? Is it more useful to search the repo than to commit files back into axlsx if it ever comes back from the dead?

**Comment by noniq** [comment]
Good question, hm.

I don't have any experience with these things: Are there any other areas where forked and “normal” repos behave differently? Would it be possible to convert the repo back to a fork, if this should ever be necessary?

**Comment by westonganger** [comment]
+1 Please move to seperate repo for searching. Should also improve SEO slightly.

**Comment by simi** [comment]
One way would be to delete repo and crate from scratch (in non-forked way). But we will lose history of issues and pull requests probably. I have inspected settings, but nothing related is present in there for my eyes. I'll contact GitHub support.

**Comment by westonganger** [comment]
https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by simi** [comment]
It should be done (thanks to GitHub support). Can you please test if search works now?

**Comment by straydogstudio** [comment]
@simi Search works as intended. Thanks for contacting support and getting that done.
