### ISSUE TITLE
iso8601 dates turning into strange floating point value?

### ISSUE THREAD

**Issue by patrick99e99** [caxlsx/caxlsx#64]
if I put a value like "2014-01-17T00:44:28.000Z" in a column, in excel/numbers it shows up as a number like: 44069.032777581

How can I make caxlsx keep it as the original iso string?

Also, the xls docs I am generating all seem to have cell information that needs to be "reparied" when being opened in excel.  I am wondering if these errors are related to the weird number formatting of dates?

**Comment by kiskoza** [comment]
Hi! There are a few solutions for your problem. First of all, we need to say that Excel stores the dates in a float calculated from 1900-01-01, so the float you're seeing _is_ the date you provided.

The first option is to provide a Date / Time object described in [Automatic Data Types example](https://github.com/caxlsx/caxlsx/blob/master/examples/automatic_data_types_example.md). This way you're data will be converted to a date, but will be shown in a default date format.

The second option is to add a `style` with a `format_code` to these date cells as descibed in [Format Codes example](https://github.com/caxlsx/caxlsx/blob/master/examples/format_codes_example.md). This was you can provide a format string, so it will look like as you wish.

The third option is to add a `type` to the cells as descibed in [Override Data Types exampe](https://github.com/caxlsx/caxlsx/blob/master/examples/override_data_types_example.md). In this case Excel won't handle the cell as a type, but as a normal string with its original value.

If you feel like adding a new option or improving these workflows, we're open to any suggestions

**Comment by patrick99e99** [comment]
thank you!
