### ISSUE TITLE
A character length error in the worksheet name when using Japanese.

### ISSUE THREAD

**Issue by sysmugen** [caxlsx/caxlsx#67]
With old version of axlsx the following name was OK.
作業員名簿(株式会社会社5)
but after update to the latest caxlsx I've got an error:
Your worksheet name '作業員名簿(株式会社会社5)' is too long. Worksheet names must be 31 characters (bytes) or less
Old version use size in validate_sheet_name(name)
`      raise ArgumentError, (ERR_SHEET_NAME_TOO_LONG % name) if name.size > 31
`
but new version use bytesize
`      raise ArgumentError, (ERR_SHEET_NAME_TOO_LONG % name) if name.bytesize > 31
`

With size: 作業員名簿(株式会社会社5) is 14
With length: 作業員名簿(株式会社会社5) is 14
With bytesize: 作業員名簿(株式会社会社5) is 36 
Each kanji has 3 bytes but same has 4 bytes.

I found that there was a commit about corrupted files when using more than 31 bytes,
but in Microsoft Office I can use multibyte name with length up to 31 characters.
Is it restriction regards to axlxs ?
Any workaround?

Best Regards.

**Comment by noniq** [comment]
The change was made because of this issue: https://github.com/randym/axlsx/issues/588

Could you investigate which restrictions Excel actually applies? Because we now have both reports indicating that unicode charaters are counted by byte (the issue mentioned above), and that they are counted per character (your issue).

**Comment by sysmugen** [comment]
Hope this link helps you.
https://github.com/PHPOffice/PhpSpreadsheet/pull/177#issuecomment-309699114

It seems that it's a Excel GUI limit not file format.
Take a look at this:
https://javarevisited.blogspot.com/2015/02/difference-between-utf-8-utf-16-and-utf.html
https://support.microsoft.com/en-gb/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
The Excel itself interprets "\u{1F1EB 1F1F7}" as 4 characters.

I think it's better to check chars rather than bytes or remove length check at all.

P.S.
Excel Worksheet Naming Rules and Tips
► Two worksheets cannot have the same name, regardless of upper or lowercase. Excel will return the error: Cannot rename a sheet to the same name as another sheet, a referenced object library or a workbook referenced by Visual Basic.
► A worksheet name cannot exceed 31 characters.
► A worksheet name cannot be left blank.
► A worksheet cannot be named history in either lower or uppercase. History is reserved by Excel for tracking changes between shared workbooks.
► Any letter from A to Z, and any number from 0 to 9 can be used.
► The following character symbols are allowed, but if the worksheet name contains a blank or any of these characters, the name must be wrapped in single quotes when manually entering formulas to link worksheet data.
`~!@#$%^&()-_=+{}|;:,<.>
(grave accent, tilde, exclamation point, at sign, pound sign, dollar sign, percent sign, caret, ampersand, left parenthesis, right parenthesis, hyphen, underscore, equal sign, plus sign, left curly brace, right curly brace, vertical bar, semi-colon, colon, comma, less than sign, period, greater than sign.)
► The apostrophe ( ' ) cannot be used at the beginning or end of a worksheet name, but can be used in the middle of a name.
► The following characters are forbidden for use when naming worksheets. Excel will not even allow you to type them:
\/?*[]:​
(backward slash, forward slash, question mark, asterisk, left bracket, right bracket, colon.)

**Comment by noniq** [comment]
Thank you for researching this!

I'm still not sure what's actually causing this problem – maybe different encodings are used? Do we know which encoding Excel uses internally when it checks the length of the title?

In #588 the reporter said that this example code results in a file that generates a warning when opened in Excel:

```ruby
require 'axlsx'

Axlsx::Package.new do |p|
  p.workbook.add_worksheet(:name => "\u{1F1EB 1F1F7}1234567890123456789012345678")
  p.serialize('bad.xlsx')
end
```

Could you try this? Does it result in a warning for you, too?

**Comment by sysmugen** [comment]
```ruby
require 'axlsx'

Axlsx::Package.new do |p|
  p.workbook.add_worksheet(:name => "\u{1F1EB 1F1F7}1234567890123456789012345678")
  p.serialize('bad.xlsx')
end
```
Excel shows a warning asking for repair and then it opens.
Sheet name changes to   🇫🇷123456789012345678901234567

```ruby
require 'axlsx'

Axlsx::Package.new do |p|
  p.workbook.add_worksheet(:name => "\u{1F1EB 1F1F7}123456789012345678901234567")
  p.serialize('bad.xlsx')
end
```
This code is OK.

**Comment by sysmugen** [comment]
`\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}`
31 chars of UTF-16
size is 31
bytesize is 93
Excel doesn't show a warning.

`\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}\u{682a}\u{5f0f}\u{4f1a}\u{793e}`
32 chars of UTF-16
size is 32
bytesize is 96
Excel does show a warning.

**Comment by noniq** [comment]
Thanks again. Do you think using `name.encode("utf-16").bytesize > 31` would fix this issue (and not cause any regressions)?

If so, would you like to create a pull request?

**Comment by sysmugen** [comment]
The following code will do the trick.
```ruby
name.encode("utf-16").bytesize/2-1 > 31
```
Please check it.

**Comment by noniq** [comment]
Looks reasonable to me. Unfortunately I don't have enough time to test and implement this right now. 

I’d be very happy if someone came up with a pull request addressing this issue 😊

**Comment by bmalets** [comment]
The same issue with Cyrillic.

**Comment by klyonrad** [comment]
I ran into this because we truncate and replace with the `…` character - and Excel opens that just fine.

**Comment by klyonrad** [comment]
By the way: Can you please be a bit more careful regarding Changelog, Commits without PR etc.?

It was quite difficult to track this down and it was a breaking change hidden in a `3.0.1 -> 3.0.2` version bump

**Comment by klyonrad** [comment]
@noniq Hey, could you please review the PR that I made?

As an alternative, if there is not enough time for the review,
I think the commit https://github.com/caxlsx/caxlsx/commit/5d3f4a9b0f8c9474459e174cf22aeb8252f444ab should be reverted and a hotfix release created because the change is not completely necessary (whoever runs into the initial problem has to take care of the title length anyway).

**Comment by bmalets** [comment]
is there any success with #70 ?
