### ISSUE TITLE
BarChart: Series name not displayed correctly

### ISSUE THREAD

**Issue by dvergeylen** [caxlsx/caxlsx#69]
Hello,

When creating a bar chart with multiple data series, the series names aren't taken into account in the legend. I tested on LibreOffice 7.0.3.1 and MS Excel for Mac 16.42 and got the same results.

Here is a reproducible test case:
```ruby
require 'axlsx'

p = Axlsx::Package.new
wb = p.workbook

wb.add_worksheet(name: 'Bar Chart') do |sheet|
  sheet.add_row ['A Simple Bar Chart']

  sheet.add_row ['', 'Jan.', 'Feb', 'March']
  sheet.add_row ['Year1', 10, 20, 30]
  sheet.add_row ['Year2', 15, 25, 35]

  sheet.add_chart(Axlsx::BarChart, start_at: 'A6', end_at: 'F20') do |chart|
    chart.barDir = :col
    chart.bg_color = 'FFFFFF'
    chart.add_series labels: sheet['B2:D2']
    chart.add_series data: sheet['B3:D3'], title: sheet['A3'], colors: ['FF0000'] * 3
    chart.add_series data: sheet['B4:D4'], title: sheet['A4'], colors: ['00FF00'] * 3
  end
end

p.serialize('/tmp/test_gem.xlsx')
```

Produces the following:

![Capture d’écran du 2020-11-10 11-30-25 (copie)](https://user-images.githubusercontent.com/8804879/98662594-4eb47980-2348-11eb-85f1-edaa10b6c815.png)

I would have expected 'Year1' and 'Year2' as series title but Libre Office displays "Ligne 3" / "Ligne 4" instead (locale FR_be). Excel displays "Serie 1" / "Serie 2". There is no color box next to them in both case.

As it's my first time using this library I might be doing something wrong (probably 😑) but reading the examples and the other issues couldn't get me further.

Would be happy to help / test. 🙂

**Comment by dvergeylen** [comment]
I could find a fix for my issue, it would be awesome if someone assesses if the fix can be generalized (and is compliant with the norm).

The problem was in `lib/axlsx/drawing/series_title.rb` file, where function `to_xml_string()` was returning an empty `'<c:f>'` markup (when `@cell` is `nil`). This confuses (at least) LibreOffice as it never reads the value in the `strCache` markup (filled in with `clean_value` variable).

```xml
<c:tx>
  <c:strRef>
    <c:f></c:f>
    <c:strCache>
      <c:ptCount val="1"/>
       <c:pt idx="0">
        <c:v>Year1</c:v>
      </c:pt>
    </c:strCache>
  </c:strRef>
</c:tx>
```

As a fix, I propose to check if `Axlsx::cell_range([@cell])` returns an empty string and, if so, replace it with `clean_value` directly:

```patch
diff --git lib/axlsx/drawing/series_title.rb lib/axlsx/drawing/series_title.rb
index 2e730de..11fad63 100644
--- lib/axlsx/drawing/series_title.rb
+++ lib/axlsx/drawing/series_title.rb
@@ -8,10 +8,11 @@ module Axlsx
     # @return [String]
     def to_xml_string(str = '')
       clean_value = Axlsx::trust_input ? @text.to_s : ::CGI.escapeHTML(Axlsx::sanitize(@text.to_s))
+      cell_range = Axlsx::cell_range([@cell])

       str << '<c:tx>'
       str << '<c:strRef>'
-      str << ('<c:f>' << Axlsx::cell_range([@cell]) << '</c:f>')
+      str << ('<c:f>' << (cell_range.empty? ? clean_value : cell_range) << '</c:f>')
       str << '<c:strCache>'
       str << '<c:ptCount val="1"/>'
       str << '<c:pt idx="0">'
```

but I don't know if this is expected behavior. It at least makes the legend to be read correctly in the spreadsheet. 🧐

**Comment by kiskoza** [comment]
In the example above, you don't need to include `chart.add_series labels: sheet['B2:D2']`, if you fix it, the titles will show the expected 'Year 1' and 'Year 2'.

Unfortunately, the `colors: [...]` attribute will change the color of the bars only, not the color of the series. I haven't found a way to do this in the current code base, so I opened a PR to add this feature.
