### ISSUE TITLE
Release 2.0.2 with fixed rubyzip dependency

### ISSUE THREAD

**Issue by noniq** [caxlsx/caxlsx#7]
In https://github.com/randym/axlsx/issues/536 it was proposed to release a version 2.0.2 containing a fix for the rubyzip dependency only, for people who cannot upgrade to axlsx 2.1 or newer.

As I mentioned in https://github.com/randym/axlsx/issues/536#issuecomment-417122751 I think that’s a good idea, but unfortunately it never happened.

Should we release a 2.0.2 version of caxlsx to give people using axlsx 2.0.1 the possibility for a simple upgrade?

**Comment by hmans** [comment]
Yes please.

**Comment by straydogstudio** [comment]
@noniq That sounds good to me.

**Comment by marisveide** [comment]
Owesome that you are doing this! Tha k you so much!
With this bumping of dependency versions, can you also make sure this new version will be able to co-exist in the same Rails project (Gemfile) with the ruby/roo (Excel reader) gem? Because axlsx recent versions can’t - they each require different rubyzip gem versions, which bundler cannot resolve...

Thank you!

**Comment by straydogstudio** [comment]
@marisveide Have you confirmed that this release of caxlsx does not coexist with ruby/roo? What version of rubyzip are you trying to use?

Caxlsx uses: s.add_runtime_dependency 'rubyzip','~> 1.2', '>= 1.2.1'
Ruby/roo uses: spec.add_dependency 'rubyzip', '>= 1.2.1', '< 2.0.0'

**Comment by marisveide** [comment]
The only _overlapping_ version is this - for `axlsx`:
`gem 'rubyzip', '~> 1.2.1'`

But that's super old and allegedly full of vulnerabilities.

Waiting for #9 to be merged/released, then will play with versions on `caxlsx`.

**Comment by straydogstudio** [comment]
@marisveide I just created a new Rails app with caxlsx, roo, and rubyzip 1.3.0. Can you give that a try?

**Comment by straydogstudio** [comment]
2.0.2 version released for new Community Axlsx (http://github.com/caxlsx/caxlsx)

**Comment by marisveide** [comment]
@straydogstudio - thank you big time! Tried - works perfectly!
Thank you so much! 👍

**Comment by noniq** [comment]
Great, thanks! 🎉
