### ISSUE TITLE
Nokogiri locked at version with active CVE

### ISSUE THREAD

**Issue by n4rq5** [caxlsx/caxlsx#74]
Recent Nokogiri CVE has no fix on 1.10 version and probably requires unlocking it to 1.11 version.

Source: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-vr8q-g5c7-m54m

**Comment by simi** [comment]
@n4rq5 nokogiri `1.11` should be supported version. Do you have any problem updating?

https://github.com/caxlsx/caxlsx/blob/cda1ce451db1c0754f1e102e1d809467c79a6d8f/axlsx.gemspec#L19

^ AFAIK means `1.x`, but equal or higher than `1.10.4`

**Comment by n4rq5** [comment]
You are absolutely right. My mistake.
For some reason bundle cannot resolve nokogiri to 1.11 on my enviroment but it lookes like caxlsx is not the culprit here. Sorry. Closing the issue now.
