### ISSUE TITLE
Low-order non-printable ASCII characters in worksheet name should be escaped or removed

### ISSUE THREAD

**Issue by khiav223577** [caxlsx/caxlsx#75]
See the original issue in axlsx: https://github.com/randym/axlsx/issues/654
I tested and found that the issue is still there in caxlsx 3.0.4.

I'm happy to prepare a pull request for it.

There are two possible fixes. Which do you prefer?
1. remove non-printable ASCII characters
2. escaping non-printable ASCII characters

**Comment by noniq** [comment]
I think they should be removed (see https://github.com/randym/axlsx/issues/654#issuecomment-680276735 ff.)

It would be great to see a PR for this!

**Comment by straydogstudio** [comment]
@khiav223577 Any possibility of a PR?

**Comment by khiav223577** [comment]
Almost forget it. I just submit a PR!
