### ISSUE TITLE
Conditional formatting seems broken for Text

### ISSUE THREAD

**Issue by DaKey-Oh** [caxlsx/caxlsx#76]
When you use text for conditional formatting and open the document the formatting does not happen.

From the Slack Channel Koza was able to confirm after a quick test that to get it to work you need to do the following:

1. Write a sample code using a text equal conditional formatting
2. Generate the excel file
3. Open it in Excel -> no formatting applied to the cells
4. Edit conditional formatting, do not touch the rules, but re-save them
5. The formatting is in place

I confirmed as well. And have attached the test as well as the default results file and the one that was fixed via the method above to get the formatting to work.

The issue is that when the file is created that text conditional should work without any user action to the file in excel.
[letter_conditional.rb.zip](https://github.com/caxlsx/caxlsx/files/5913038/letter_conditional.rb.zip)
[conditional_letters_example_manual_rule_save_now_works.xlsx](https://github.com/caxlsx/caxlsx/files/5913040/conditional_letters_example_manual_rule_save_now_works.xlsx)
[conditional_letters_example.xlsx](https://github.com/caxlsx/caxlsx/files/5913043/conditional_letters_example.xlsx)

MacOS 10.14.6 MoJave 
MS Excel for Mac 16.44 (20121301)
caxlsx (3.0.4)
![Screen Shot 2021-02-02 at 10 34 26 AM](https://user-images.githubusercontent.com/78437670/106638852-4ee0a180-6552-11eb-98dd-963927359d9e.png)
![Screen Shot 2021-02-02 at 10 33 37 AM](https://user-images.githubusercontent.com/78437670/106638861-5142fb80-6552-11eb-9514-eaeebe7e30a6.png)

Koza  Mentioned below
The missing xml-fragment seems to be this one:
`<formula>NOT(ISERROR(SEARCH("Profit",A1)))</formula>`

**Comment by kiskoza** [comment]
Related issues: https://github.com/randym/axlsx/issues/645 and https://github.com/randym/axlsx/issues/566 (maybe more, it seems to be an old one)

When I resaved my generated file, this seemed to be the main code change in it, a `formula` was added. Copying this to the "bad" file, it started to work.

```xml
<conditionalFormatting sqref="A1:J1">
    <cfRule type="containsText" dxfId="1" priority="1" operator="containsText" text="Profit">
        <formula>NOT(ISERROR(SEARCH("Profit",A1)))</formula>
    </cfRule>
</conditionalFormatting>
```

Official standard is [ISO/IEC 29500-1:2016](https://standards.iso.org/ittf/PubliclyAvailableStandards/index.html)

Next step could be to check the standard to see what should be in the formula, or is it mandatory to be there

**Comment by randym** [comment]
You need to fix the operator and specify a formula.
Might be worth adding an example.

```ruby

require 'caxlsx'

p = Axlsx::Package.new
wb = p.workbook

s = wb.styles
style_ok = s.add_style(:bg_color => "002760", :fg_color => "FF428751", :type => :dxf )

wb.add_worksheet(name: 'Text Matching Conditional') do |sheet|
  sheet.add_row ["A","B"]
  sheet.add_row ["B","A"]

  # 1. You must specify :containsText for both type and operator.
  #
  # 2. You must craft a formula to match what you are looking for. In this case we only need to
  # reference the top-left cell of the range.
  #
  # 3. Formula can be very vender specific. You will want to test extensively if
  # interoperability beyond excel is a concern.

  sheet.add_conditional_formatting 'A1:B2',
    type: :containsText,
    operator: :containsText,
    formula:'NOT(ISERROR(SEARCH("A",A1)))',
    dxfId: style_ok,
    priority: 1

end

p.serialize 'conditional_formatting_text_matching_example.xlsx'

**Comment by kiskoza** [comment]
Cool, I'll add this as an example

**Comment by noniq** [comment]
0146438 adds an additional example explaining how to do this.
