### ISSUE TITLE
 Fix Relationship.instances cache

### ISSUE THREAD

**Issue by klyonrad** [caxlsx/caxlsx#8]
Hot stuff with this project!

Do you think you could add the changes from this PR from @marshall-lee ? https://github.com/randym/axlsx/pull/477

**Comment by straydogstudio** [comment]
@klyonrad I expect we can.

**Comment by marshall-lee** [comment]
Should I re-create a PR here or you'll cherry-pick?

**Comment by straydogstudio** [comment]
Thanks @marshall-lee. That would be great if you could. If you don't, I will get to it in the next week.

**Comment by marshall-lee** [comment]
@straydogstudio PR: #10

**Comment by straydogstudio** [comment]
@klyonrad @marshall-lee Merged. I'll get tests working and release a new 3.0.1 today. 

@marshall-lee @noniq Any thoughts on version number? Should it be 3.1 with this instances cache change? It's not really a bug fix.

**Comment by noniq** [comment]
Not sure. Does this PR add new functionality? Then a minor version bump would be justified / needed.

**Comment by straydogstudio** [comment]
Figured it's really a fix. 3.0.1 released with this pull request.
