### ISSUE TITLE
number String like '00063' will lost leading zero when output with style: format_code: '@'

### ISSUE THREAD

**Issue by yg7001** [caxlsx/caxlsx#86]
how to prevent caxlsx to lost the leading zero？

**Comment by kiskoza** [comment]
hi @yg7001 . You should check our [Override data types](https://github.com/caxlsx/caxlsx/blob/master/examples/override_data_types_example.md) example

**Comment by yg7001** [comment]
> hi @yg7001 . You should check our [Override data types](https://github.com/caxlsx/caxlsx/blob/master/examples/override_data_types_example.md) example

Thanks alot！ That resolves my problem.

**Comment by rubyonrailsworks** [comment]
@kiskoza Hi @kiskoza , which clicking on the value, it will be converted to number.,
![image](https://github.com/user-attachments/assets/03f9e8ee-17cf-4bc7-afa4-0cf99ae74563)
![image](https://github.com/user-attachments/assets/4c8b1613-54de-43bf-bc12-4c74ea395782)

`I set the cell row style to '@' and the type to :string
`
