### ISSUE TITLE
How to set a cell's value starting with =

### ISSUE THREAD

**Issue by jean-marc-voillequin** [caxlsx/caxlsx#90]
Hello,

When i try to create a cell with a value starting with '=', i get an error in the resulting .xlsx (see attached image).

```
require 'caxlsx'
axlsx = Axlsx::Package.new
workbook = axlsx.workbook
sheet = workbook.add_worksheet(:name => 'mysheet')
row = sheet.add_row
cell = row.add_cell("=<200")
axlsx.use_shared_strings = true
axlsx.serialize('a.xlsx')

```
![Capture](https://user-images.githubusercontent.com/56127093/111967680-9e762f00-8af8-11eb-9f49-c0327bac93ce.PNG)

As the value is starting with '=', I guess Excel try to interpret it as a formula. But it's not a formula. Just a string starting with '='.
When i escape the value with a single quote, i get a single quote in the resulting workbook.
Is there a nice trick to avoid that?

Thanks and regards

**Comment by kiskoza** [comment]
Hi. Please check our [Escape Formula Example](https://github.com/caxlsx/caxlsx/blob/master/examples/escape_formula_example.md), it does the trick you looking for.

**Comment by jean-marc-voillequin** [comment]
It works like a charm! Thanks a lot kiskoza.
