### ISSUE TITLE
License issue with mimemagic

### ISSUE THREAD

**Issue by herwinw** [caxlsx/caxlsx#92]
Mimemagic updated its license today to GPL2, which affects al software using this library. And caxlsx does depend on that gem.

https://github.com/rails/rails/pull/41751/files does include an example of replacing the gem with mime-types, which looks pretty much like a drop-in-replacement.

**Comment by summera** [comment]
@noniq @straydogstudio any thoughts on this? Rails seems to be going with a different approach - https://github.com/rails/rails/issues/41750#issuecomment-805977682. I think that's being tested out here - https://github.com/rails/marcel/pull/26

**Comment by kiskoza** [comment]
I found a promising [fork of mimemagic](https://github.com/jellybob/mimemagic) which tries to get the gem under the right licensing, as far as I know they will release a new 0.3.x version soon

**Comment by jpac-run** [comment]
A new version of mimemagic with the MIT license was released: [0.3.7](https://github.com/mimemagicrb/mimemagic/tree/v0.3.7)

**Comment by kiskoza** [comment]
Update: [Mimemagic 0.3.7](https://rubygems.org/gems/mimemagic/versions/0.3.7) has been released under the MIT license. We should check that out and change the dependencies accordingly.

**Comment by straydogstudio** [comment]
I am assuming we should go the same direction as Rails long term. The new mimemagic loads the "magic" at runtime, which they are not disposed to do. Can we wait until the dust has settled?

**Comment by noniq** [comment]
Now that 0.3.7 hase been released, do we still need to take immediate action? As far as I understand bundle installs and deploys should now work again (people might have to run `bundle update`, but that would be necessary anyway).

In the long term I’m also in favour of finding a solution that does not impose additional prerequisites at install time.

**Comment by straydogstudio** [comment]
@noniq I am equally in favor of a better long term solution. 👍

**Comment by campbecf** [comment]
I found this comment on Reddit to be useful context: https://www.reddit.com/r/ruby/comments/mc5bpe/mimemagic_versions_prior_to_036_have_been_yanked/gs6y5y4/

**Comment by straydogstudio** [comment]
Version 3.1.0 has been released
