### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by johnnyshields** [caxlsx/caxlsx#96]
Mimemagic / Marcel fix would be nice to have in an officially released version.

**Comment by straydogstudio** [comment]
@johnnyshields Just released 3.1.0 this morning with the marcel dependency:

https://github.com/caxlsx/caxlsx/blob/master/axlsx.gemspec#L22

https://rubygems.org/gems/caxlsx

Let us know if you have issues with it.

**Comment by straydogstudio** [comment]
Several other features made it into the release: https://github.com/caxlsx/caxlsx/blob/master/CHANGELOG.md

**Comment by johnnyshields** [comment]
Thank you 🎉
